#-------------------------------------------------------------------------------------------------------------------------------------------
# This file contains all properties that are NOT injected by Gradle. These go into application.properties, since Gradle's expand()
# does not play well with YAML.
#
# Spring Boot reads both application.properties and application.yml.
#-------------------------------------------------------------------------------------------------------------------------------------------

codekvast:
    dnsCname:                    localhost
    environment:                 dev

logging:
    file:
        name: build/log/rule-engine.log
    level:
        io.codekvast: DEBUG

management:
    endpoints:
        enabled-by-default: true
        jmx:
            domain: CodekvastRuleEngine
        web:
            base-path:        /management
            exposure.include: '*'
    endpoint:
        health:
            show-details:       "ALWAYS"
            cache.time-to-live: 1s
    server:
        port: 9080
    metrics:
        web.server.request.autotime.enabled: true
        export.datadog.enabled:        false
        tags:
            service: "codekvast-rule-engine"
            env:     dev
            host:    localhost

server:
    port:                8080
    servlet:
        context-path: /
        session:
            cookie:
                max-age: 10m
            persistent: false
    undertow:
        accesslog:
            dir:     build/log
            enabled: true
            pattern: combined
            prefix:  access.
    forward-headers-strategy: framework
    error:
        whitelabel:
            enabled: false

spring:
    application.name:    Codekvast Rule Engine
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
        password: codekvast
        url:      jdbc:mariadb://localhost/codekvast
        username: codekvast
    rabbitmq:
        addresses: "amqp://admin:secret@localhost:5672"
        template:
            retry:
                enabled: true
                initial-interval: 2s
        listener:
            simple:
                default-requeue-rejected: false

    flyway:
        validate-on-migrate: false
    groovy.template.configuration:
        auto-new-line: true
        auto-indent:   true
    http:
        converters.preferred-json-mapper: gson
        log-request-details:              true
    output.ansi.enabled: detect
