spring:
  application.name:    Codekvast Stress Tester
  datasource:
    url:      jdbc:mariadb://localhost/codekvast
    username: codekvast
    password: codekvast
  profiles:
    include: no-slack-integration
  rabbitmq:
    addresses: "amqp://admin:secret@localhost:5672"
    template:
      retry:
        enabled:          true
        initial-interval: 2s
  flyway:
    validate-on-migrate: false
management:
  metrics:
    export:
      datadog:
        enabled: false
logging:
  file:
    name: build/log/stress-tester.log
  level:
    io.codekvast: INFO

codekvast:
  stress-tester:
    eventRateMillis: 50