---
- name: Setting timezone to UTC
  timezone: name=UTC

- name: Create codekvast group
  group: name=codekvast state=present

- name: Create codekvast user
  user: name=codekvast group=codekvast state=present home=/opt/codekvast

- name: Install Python3
  package: name=python3 state=present

- name: Install pip3
  package: name=python3-pip state=present

- name: Make Python3 default
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/usr/bin/{{ item }}3"
  with_items:
  - python
  - pip

- name: Install datadogpy
  pip: name=datadog

- name: Remove Python2
  package: name=python2.7 state=absent
