# meta file for hostname
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Manage a swap file in Debian-like systems
  license: MIT
  min_ansible_version: 2.2.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - system
dependencies: []
