---
- name: "Building {{ stack.env }} stack for customer '{{ stack.customer }}'"
  debug: var=stack
  when: _debug is defined and _debug

- name: Create VPC
  local_action:
    module: ec2_vpc_net
    region: "{{ aws_region }}"
    profile: codekvast
    state: "{{ stack.state }}"
    name: "{{ aws_stack_name }}"
    cidr_block: "{{ stack.cidr_base }}.0.0/16"
    tags: "{{ aws_common_tags }}"
  register: net

- debug: var=net
  when: _debug is defined and _debug

- set_fact: vpc_id="{{ net.vpc.id }}"

- name: Create VPC internet gateway
  local_action:
    module: ec2_vpc_igw
    region: "{{ aws_region }}"
    profile: codekvast
    state: "{{ stack.state }}"
    vpc_id: "{{ vpc_id }}"
  register: igw

- debug: var=igw
  when: _debug is defined and _debug

- name: Create VPC subnet A
  local_action:
    module: ec2_vpc_subnet
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    az: "{{ aws_region }}a"
    cidr: "{{ stack.cidr_base }}.1.0/24"
    resource_tags: "{{ aws_common_tags }}"
  register: subnet

- debug: var=subnet
  when: _debug is defined and _debug

- set_fact: subnet_id_a="{{ subnet.subnet.id }}"

- name: Create VPC subnet B
  local_action:
    module: ec2_vpc_subnet
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    az: "{{ aws_region }}b"
    cidr: "{{ stack.cidr_base }}.2.0/24"
    resource_tags: "{{ aws_common_tags }}"
  register: subnet

- debug: var=subnet
  when: _debug is defined and _debug

- set_fact: subnet_id_b="{{ subnet.subnet.id }}"

- name: Create subnet route table
  local_action:
    module: ec2_vpc_route_table
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    tags: "{{ aws_common_tags }}"
    subnets:
      - "{{ subnet_id_a }}"
      - "{{ subnet_id_b }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: route_table

- debug: var=route_table
  when: _debug is defined and _debug

- name: Create frontend security group
  local_action:
    module: ec2_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    name: "codekvast-{{ stack.customer }}-{{ stack.env }}-frontend"
    description: "Codekvast internet-facing security group"
    rules:
    - proto: tcp
      ports:
      - 443
      cidr_ip: 0.0.0.0/0

- name: Create backend security group
  local_action:
    module: ec2_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    name: "codekvast-{{ stack.customer }}-{{ stack.env }}-backend"
    description: "Codekvast backend access"
    rules:
    - proto: tcp
      ports:
      - 8080
      - 8081
      group_name: "codekvast-{{ stack.customer }}-{{ stack.env }}-frontend"
      group_desc: "Codekvast internet-facing security group"
    - proto: tcp
      ports:
      - 8080
      - 8081
      - 9080
      - 9081
      group_name: "codekvast-{{ stack.customer }}-{{ stack.env }}-management"
      group_desc: "Codekvast management access"

- name: Create database security group
  local_action:
    module: ec2_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    name: "codekvast-{{ stack.customer }}-{{ stack.env }}-database"
    description: "Codekvast database access"
    rules:
    - proto: tcp
      ports:
      - 3306
      group_name: "codekvast-{{ stack.customer }}-{{ stack.env }}-backend"
      group_desc: "Codekvast backend access"

- name: curl http://whatismyip.akamai.com/
  uri:
    url: http://whatismyip.akamai.com/
    return_content: yes
  register: my_ip
  changed_when: false

- debug: var=my_ip
  when: _debug is defined and _debug

- name: Create management security group
  local_action:
    module: ec2_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    state: "{{ stack.state }}"
    name: "codekvast-{{ stack.customer }}-{{ stack.env }}-management"
    description: "Codekvast management access"
    purge_rules: false
    rules:
    - proto: tcp
      ports:
      - 22
      - 3306
      - 8080
      - 8081
      - 9080
      - 9081
      cidr_ip: "{{ my_ip.content }}/32"

- set_fact:
    role_tag_database:
      Name: "Codekvast-{{ stack.customer }}-{{ stack.env }}-database"
      role: "database"
      Customer: "{{ stack.customer }}"
      Env: "{{ stack.env }}"
      Owner: Codekvast
    role_tag_backend:
      Name: "Codekvast-{{ stack.customer }}-{{ stack.env }}-backend"
      role: "backend"
      Customer: "{{ stack.customer }}"
      Env: "{{ stack.env }}"
      Owner: Codekvast

- name: Create EC2 database instance
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    profile: codekvast # in ~/.boto
    key_name: codekvast
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet_id_a }}"
    groups:
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-database"
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-management"
    image: "{{ aws_ami_id }}"
    instance_type: "{{ stack.db_instance_type }}"
    instance_profile_name: "{{ ec2_instance_profile_name }}"
    user_data: "{{ lookup('file', 'files/ubuntu-cloud-init.sh') }}"
    exact_count: 1
    count_tag: "{{ role_tag_database }}"
    instance_tags: "{{ role_tag_database }}"
    termination_protection: "{{ ('no', 'yes')[stack.env == 'prod'] }}"
    wait: yes
  register: ec2database

- debug: var=ec2database
  when: _debug is defined and _debug

- set_fact: database_instance_id="{{ ec2database.tagged_instances[0].id }}"

- debug: var=database_instance_id
  when: _debug is defined and _debug

#----------------------------------
- name: "Create EC2 backend instances in {{ aws_region }}a"
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    profile: codekvast # in ~/.boto
    key_name: codekvast
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet_id_a }}"
    groups:
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-backend"
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-management"
    image: "{{ aws_ami_id }}"
    instance_type: "{{ stack.backend_instance_type }}"
    instance_profile_name: "{{ ec2_instance_profile_name }}"
    user_data: "{{ lookup('file', 'files/ubuntu-cloud-init.sh') }}"
    exact_count: "{{ stack.backend_count_a | default(1) }}"
    count_tag: "{{ role_tag_backend }}"
    instance_tags: "{{ role_tag_backend }}"
    termination_protection: "{{ ('no', 'yes')[stack.env == 'prod'] }}"
    wait: yes
  register: ec2backends_a

#-----------------------------------
- name: "Create EC2 backend instances in {{ aws_region }}b"
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    profile: codekvast # in ~/.boto
    key_name: codekvast
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet_id_b }}"
    groups:
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-backend"
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-management"
    image: "{{ aws_ami_id }}"
    instance_type: "{{ stack.backend_instance_type }}"
    instance_profile_name: "{{ ec2_instance_profile_name }}"
    user_data: "{{ lookup('file', 'files/ubuntu-cloud-init.sh') }}"
    exact_count: "{{ stack.backend_count_b | default(1) }}"
    count_tag: "{{ role_tag_backend }}"
    instance_tags: "{{ role_tag_backend }}"
    termination_protection: "{{ ('no', 'yes')[stack.env == 'prod'] }}"
    wait: yes
  register: ec2backends_b

- debug: var=ec2backends_a
  when: _debug is defined and _debug

- debug: var=ec2backends_b
  when: _debug is defined and _debug

- set_fact:
    ec2backends: "{{ ec2backends_a.tagged_instances }} + {{ ec2backends_b.tagged_instances }}"

- debug: var=ec2backends
  when: _debug is defined and _debug

- set_fact:
    backend_ids: "{{ backend_ids|default([]) + [{'Id': item }] }}"
  with_items: "{{ ec2backends_a.tagged_instances|map(attribute='id') | list }} + {{ ec2backends_b.tagged_instances|map(attribute='id') | list }}"

- debug: var=backend_ids
  when: _debug is defined and _debug

#-----------------------------------
#- name: Refresh external EC2 cache
#  command: "{{ inventory_dir }}/ec2.py --refresh-cache"
#  when: ec2database.changed or ec2backends.changed

#- name: Refresh in-memory EC2 cache
#  meta: refresh_inventory
#  when: ec2database.changed or ec2backends.changed

- name: "Create ALB target group for api/dashboard"
  local_action:
    module: elb_target_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    name: "{{ aws_target_group_dashboard }}"
    protocol: http
    port: "{{ ports.dashboard.service }}"
    health_check_protocol: http
    health_check_port: "{{ ports.dashboard.management }}"
    health_check_path: /management/health
    health_check_interval: 10
    health_check_timeout: 2
    healthy_threshold_count: 2
    unhealthy_threshold_count: 3
    state: present
    stickiness_enabled: no
    tags: "{{ aws_common_tags }}"
    target_type: instance
    targets: "{{ backend_ids }}"

- name: "Create ALB target group for login"
  local_action:
    module: elb_target_group
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    name: "{{ aws_target_group_login }}"
    protocol: http
    port: "{{ ports.login.service }}"
    health_check_protocol: http
    health_check_port: "{{ ports.login.management }}"
    health_check_path: /management/health
    health_check_interval: 10
    health_check_timeout: 2
    healthy_threshold_count: 2
    unhealthy_threshold_count: 3
    state: present
    stickiness_enabled: yes
    stickiness_lb_cookie_duration: 300
    stickiness_type: lb_cookie
    tags: "{{ aws_common_tags }}"
    target_type: instance
    targets: "{{ backend_ids }}"

- name: Destroy Elastic Load Balancer
  local_action:
    module: ec2_elb_lb
    region: "{{ aws_region }}"
    profile: codekvast
    name: "{{ aws_stack_name }}"
    state: absent

- name: Create Application Load Balancer
  local_action:
    module: elb_application_lb
    region: "{{ aws_region }}"
    profile: codekvast
    name: "{{ aws_stack_name }}"
    state: present
    deletion_protection: "{{ ('no', 'yes')[stack.env == 'prod'] }}"
    scheme: internet-facing
    security_groups:
    - "codekvast-{{ stack.customer }}-{{ stack.env }}-frontend"
    state: present
    subnets:
    - "{{ subnet_id_a }}"
    - "{{ subnet_id_b }}"
    tags: "{{ aws_common_tags }}"
    listeners:
    - Protocol: HTTPS
      Port: 443
      Certificates:
      - CertificateArn: "{{ ssl_certificate_id }}"
      SslPolicy: ELBSecurityPolicy-2015-05
      DefaultActions:
      - Type: forward
        TargetGroupName: "{{ aws_target_group_dashboard }}"
      Rules:
        - Conditions:
          - Field: host-header
            Values:
            - "{{ stack.app_cnames[1] }}.codekvast.io"
          Priority: '1'
          Actions:
          - Type: forward
            TargetGroupName: "{{ aws_target_group_login }}"
    wait: yes
  register: alb

- debug: var=alb
  when: _debug is defined and _debug

- set_fact: alb_dns_name="{{ alb.dns_name }}"

- name: Define load balancer's CNAMEs
  local_action:
    module: route53
    profile: codekvast # in ~/.boto
    command: create
    overwrite: yes
    record: "{{ item }}.codekvast.io"
    value: "{{ alb_dns_name }}"
    ttl: 3600
    type: CNAME
    zone: codekvast.io
  with_items: "{{ stack.app_cnames }}"

- name: Define database instances' CNAMEs
  local_action:
    module: route53
    profile: codekvast # in ~/.boto
    command: create
    overwrite: yes
    record: "{{ stack.db_cname }}{{ '%02d'|format(item.0) }}.codekvast.io"
    value: "{{ item.1.public_dns_name }}"
    ttl: 600
    type: CNAME
    zone: codekvast.io
  with_indexed_items: "{{ ec2database.tagged_instances }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Tag database instances with their CNAMEs
  local_action:
    module: ec2_tag
    region: "{{ aws_region }}"
    profile: codekvast # in ~/.boto
    resource: "{{ item.1.id }}"
    tags:
      CNAME: "{{ stack.db_cname }}{{ '%02d'|format(item.0) }}.codekvast.io"
  with_indexed_items: "{{ ec2database.tagged_instances }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Define api CNAMEs
  local_action:
    module: route53
    profile: codekvast # in ~/.boto
    command: create
    overwrite: yes
    record: "{{ stack.app_cnames[0] }}{{ '%02d'|format(item.0) }}.codekvast.io"
    value: "{{ item.1.public_dns_name }}"
    ttl: 60
    type: CNAME
    zone: codekvast.io
  with_indexed_items: "{{ ec2backends }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Define login CNAMEs
  local_action:
    module: route53
    profile: codekvast # in ~/.boto
    command: create
    overwrite: yes
    record: "{{ stack.app_cnames[1] }}{{ '%02d'|format(item.0) }}.codekvast.io"
    value: "{{ item.1.public_dns_name }}"
    ttl: 60
    type: CNAME
    zone: codekvast.io
  with_indexed_items: "{{ ec2backends }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Define dashboard CNAMEs
  local_action:
    module: route53
    profile: codekvast # in ~/.boto
    command: create
    overwrite: yes
    record: "{{ stack.app_cnames[2] }}{{ '%02d'|format(item.0) }}.codekvast.io"
    value: "{{ item.1.public_dns_name }}"
    ttl: 60
    type: CNAME
    zone: codekvast.io
  with_indexed_items: "{{ ec2backends }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Tag application instances with their CNAMEs
  local_action:
    module: ec2_tag
    region: "{{ aws_region }}"
    profile: codekvast # in ~/.boto
    resource: "{{ item.1.id }}"
    tags:
      CNAME: "{{ stack.app_cnames[0] }}{{ '%02d'|format(item.0) }}.codekvast.io"
      CNAME0: "{{ stack.app_cnames[0] }}{{ '%02d'|format(item.0) }}.codekvast.io"
      CNAME1: "{{ stack.app_cnames[1] }}{{ '%02d'|format(item.0) }}.codekvast.io"
      CNAME2: "{{ stack.app_cnames[2] }}{{ '%02d'|format(item.0) }}.codekvast.io"
      LBCNAME: "{{ stack.app_cnames[0] }}.codekvast.io"
      LBCNAME0: "{{ stack.app_cnames[0] }}.codekvast.io"
      LBCNAME1: "{{ stack.app_cnames[1] }}.codekvast.io"
      LBCNAME2: "{{ stack.app_cnames[2] }}.codekvast.io"
  with_indexed_items: "{{ ec2backends }}"
  loop_control:
    label: "{{ item.1.public_dns_name }}"

- name: Create S3 bucket for database backups
  local_action:
    module: s3_bucket
    region: "{{ aws_region }}"
    profile: codekvast
    name: "{{ s3_database_backup_bucket }}"
    tags: "{{ aws_common_tags }}"

- name: Wait for OpenSSH on EC2 instances
  local_action:
    module: wait_for
    host: "{{ item }}"
    port: 22
    search_regex: OpenSSH
  with_items:
  - "{{ ec2database.tagged_instances|map(attribute='public_ip') | list }}"
  - "{{ ec2backends|map(attribute='public_ip') | list }}"
