codekvast:
  common:
    dashboardBaseUrl:                         http://localhost:8081
    dnsCname:                                 localhost
    environment:                              dev
    jwtSecret:                                secret
    loginBaseUrl:                             http://localhost:8080
    slackWebhookToken:

logging:
  file:
    name: build/log/application.log
  level:
    io.codekvast: DEBUG
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG

spring:
  profiles:
    include: color-logging,json-logging-file
  datasource:
    password: codekvast
    url:      jdbc:mariadb://localhost/codekvast
  rabbitmq:
    addresses: "amqp://admin:secret@localhost:5672"
  cache:
    caffeine:
      spec: 'expireAfterAccess=10s'

server:
  undertow:
    accesslog:
      dir:     build/log
      prefix:  access.

management:
  metrics:
    tags:
      host:    localhost
      env:     dev
    web.server.request.autotime.enabled: true
    export.datadog.enabled:              false
