# This profile is activated when deployed to AWS ECS Fargate.
codekvast:
  common:
    heapDumpUploaderDelaySeconds:    60
    heapDumpUploaderIntervalSeconds: 60
logging:
  level:
    io.codekvast:                                         INFO
    # io.codekvast.common.aspects.HealthCheckLoggingAspect: DEBUG
    io.micrometer.datadog.DatadogMeterRegistry:           OFF
    org.springframework.boot.actuate:                     INFO

management:
  server:
    port: 9080
  endpoint:
    beans.enabled:      false
    conditions.enabled: false
    mappings.enabled:   false
  metrics:
    export:
      datadog:
        enabled:  true
        step:     1m
        host-tag: host
      jmx:
        enabled: false
server:
  port: 8080
  undertow:
    threads:
      io:     100
      worker: 100
spring:
  main:
    banner-mode: off
