---
- name: Test AWS CLI
  shell: env HOME=/home/{{ actual_username }} aws --profile {{ item }} ec2 describe-availability-zones
  with_items:
  - codekvast

- name: Relogin needed
  debug: msg='You need to logout and login'
