package se.crisp.codekvast.agent.main.codebase;

import lombok.extern.slf4j.Slf4j;
import org.reflections.Reflections;
import org.reflections.scanners.SubTypesScanner;
import org.springframework.stereotype.Component;
import se.crisp.codekvast.agent.util.SignatureUtils;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.net.URLClassLoader;
import java.util.Set;

/**
 * Analyzes a code base and detects public methods. Uses the org.reflections for retrieving method signature data.
 *
 * It also contains support for mapping synthetic methods generated by runtime byte code manipulation frameworks back to the declared method
 * as it appears in the source code.
 *
 * @author Olle Hallin
 */
@Slf4j
@Component
public class CodeBaseScanner {

    void getPublicMethodSignatures(CodeBase codeBase) {
        URLClassLoader appClassLoader = new URLClassLoader(codeBase.getUrls(), System.class.getClassLoader());
        Set<String> prefixes = codeBase.getConfig().getNormalizedPackagePrefixes();

        long startedAt = System.currentTimeMillis();
        Set<String> recognizedTypes = getRecognizedTypes(prefixes, appClassLoader);
        for (String type : recognizedTypes) {
            try {
                Class<?> clazz = Class.forName(type, false, appClassLoader);
                findPublicMethods(codeBase, prefixes, clazz);
            } catch (ClassNotFoundException e) {
                log.warn("Cannot analyze " + type, e);
            }
        }
        codeBase.setNumClasses(recognizedTypes.size());
        log.info("Found {} methods in {} classes in packages {} in {} ms", codeBase.getSignatures().size(), recognizedTypes.size(),
                 prefixes, System
                .currentTimeMillis() - startedAt);
    }


    private Set<String> getRecognizedTypes(Set<String> packagePrefixes, URLClassLoader appClassLoader) {
        RecordingClassFileFilter recordingClassNameFilter = new RecordingClassFileFilter(packagePrefixes);
        new Reflections(appClassLoader, new SubTypesScanner(), recordingClassNameFilter);
        return recordingClassNameFilter.getMatchedClassNames();
    }

    void findPublicMethods(CodeBase codeBase, Set<String> packagePrefixes, Class<?> clazz) {
        log.debug("Analyzing {}", clazz);
        try {
            Method[] methods = clazz.getMethods();

            for (Method method : methods) {
                if (Modifier.isPublic(method.getModifiers())) {

                    // Some AOP frameworks (e.g., Guice) push methods from a base class down to the subclasses created in runtime.
                    // We need to map those back to the original declaring signature, or else the original,
                    // declared method will look unused.

                    String thisSignature = SignatureUtils.makeSignatureString(clazz, method);
                    String declaringSignature =
                            SignatureUtils.makeSignatureString(findDeclaringClass(method.getDeclaringClass(), method, packagePrefixes),
                                                               method);

                    codeBase.addSignature(thisSignature, declaringSignature);
                }
            }

            for (Class<?> innerClass : clazz.getDeclaredClasses()) {
                findPublicMethods(codeBase, packagePrefixes, innerClass);
            }
        } catch (NoClassDefFoundError e) {
            log.warn("Cannot analyze {}: {}", clazz, e.toString());
        }
    }

    private Class findDeclaringClass(Class<?> clazz, Method method, Set<String> packagePrefixes) {
        if (clazz == null) {
            return null;
        }
        String pkg = clazz.getPackage().getName();

        boolean found = false;
        for (String prefix : packagePrefixes) {
            if (pkg.startsWith(prefix)) {
                found = true;
                break;
            }
        }

        if (!found) {
            return null;
        }

        try {
            clazz.getDeclaredMethod(method.getName(), method.getParameterTypes());
            return clazz;
        } catch (NoSuchMethodException ignore) {
        }
        return findDeclaringClass(clazz.getSuperclass(), method, packagePrefixes);
    }

}
