# {{ ansible_managed }}

codekvast:
  jwtExpirationHours: "{{ codekvast_jwtExpirationHours }}"
  jwtSecret: "{{ codekvast_jwtSecret }}"
  dnsCname: "{{ tags.CNAME3 }}"
  environment: "{{ tags.Env }}"
  slackWebHookToken: "{{ codekvast_slackWebhookToken }}"

logging:
  file:
    name: "/var/log/codekvast/{{ service_name }}/application.log"
    max-size: '10MB'
    max-history: 10
  level:
    io.codekvast: "{{ 'DEBUG' if tags.Env == 'staging' else 'INFO' }}"
    io.micrometer.datadog.DatadogMeterRegistry: OFF

management:
  server.port: "{{ management_port }}"
  endpoint:
    beans.enabled: false
    conditions.enabled: false
    mappings.enabled: false
  metrics:
    tags:
      service: "codekvast-{{ service_name }}"
      env: "{{ tags.Env }}"
      host: "{{ tags.CNAME3 }}"
    export.datadog:
      api-key: "{{ datadog_api_key }}"
      enabled: true
      step: PT60S

server:
  port: "{{ service_port }}"
  undertow.accesslog:
    dir: "/var/log/codekvast/{{ service_name }}/"
    prefix: access.

spring:
  datasource:
    password: "{{ mariadb_application_password }}"
    url: "jdbc:mariadb://{{ rds_endpoint_address }}/codekvast"

  rabbitmq:
    addresses: "{{ rabbitmq[tags.Env].url}}"
    template:
      retry:
        enabled: true
        initial-interval: 2s

  mail:
    username: "{{ aws.credentials.ses.username }}"
    password: "{{ aws.credentials.ses.password }}"
