version: '3.7'

volumes:
    database:
        driver: local
    rabbitmq:
        driver: local

services:
    database:
        image: mariadb:10.4.25
        restart: unless-stopped
        environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_DATABASE=codekvast"
        - "MYSQL_USER=codekvast"
        - "MYSQL_PASSWORD=codekvast"
        - "MYSQL_INITDB_SKIP_TZINFO=true"
        - "TERM=xterm-256color"
        volumes:
        - database:/var/lib/mysql
        ports:
        - '3306:3306'
        command: "
        --slow_query_log=1
        --log_output=TABLE
        --log_queries_not_using_indexes=ON
        --character-set-server=utf8
        --performance_schema=ON
        --performance-schema-instrument='stage/%=ON'
        --performance-schema-consumer-events-stages-current=ON
        --performance-schema-consumer-events-stages-history=ON
        --performance-schema-consumer-events-stages-history-long=ON"

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        restart: unless-stopped
        environment:
        - "RABBITMQ_DEFAULT_VHOST=/"
        - "RABBITMQ_DEFAULT_USER=admin"
        - "RABBITMQ_DEFAULT_PASS=secret"
        volumes:
          - rabbitmq:/var/lib/rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
