#-------------------------------------------------------------------------------------------------------------------------------------------
# This file contains all properties that are NOT injected by Gradle. These go into application.properties, since Gradle's expand()
# does not play well with YAML.
#
# Spring Boot reads both application.properties and application.yml.
#-------------------------------------------------------------------------------------------------------------------------------------------

management:
  health:
    mail:
      enabled: true

spring:
  application.name:    Codekvast Backoffice
  profiles:
    include: common
