#-------------------------------------------------------------------------------------------------------------------------------------------
# This file contains all properties that are NOT injected by Gradle. These go into application.properties, since Gradle's expand()
# does not play well with YAML.
#
# Spring Boot reads both application.properties and application.yml.
#-------------------------------------------------------------------------------------------------------------------------------------------

management:
  server:
    port: 9082
  metrics:
    tags:
      service: "codekvast-backoffice"
      env:     dev
      host:    localhost

server:
  port:                     8082

spring:
  application.name:    Codekvast Backoffice
  profiles:
    include: common
