import io.codekvast.backoffice.facts.CollectionStarted
import io.codekvast.backoffice.facts.UserAuthenticated
import io.codekvast.common.messaging.model.CodekvastEvent
import io.codekvast.common.messaging.model.CollectionStartedEvent
import io.codekvast.common.messaging.model.UserAuthenticatedEvent

global java.time.Clock clock
global Long customerId
global io.codekvast.backoffice.service.MailSender mailSender

rule "Collection has started"
when
  $cse: CollectionStartedEvent()
  not(CollectionStarted())
then
   insert(CollectionStarted.of($cse));
end

rule "Send welcome mail when collection has started"
when
  $cs: CollectionStarted(welcomeMailSent == false)
then
  mailSender.sendMail("welcome-collection-has-started", customerId);
  modify($cs) {
    setWelcomeMailSent(true)
  }
end

rule "Retract transient event facts"
salience -1000
when
  $ce: CodekvastEvent()
then
   retract($ce)
end
