---
- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: "restart codekvast service"
  # Not possible to have more than one task in a handler, so they are in a separate file.
  include_tasks: handler-restart-codekvast-service.yml
