codekvast:
  login:
    cipherSecret: someCipherSecret
    herokuApiPassword: herokuApiPassword
    herokuApiSsoSalt: herokuApiSsoSalt
    herokuCodekvastUrl: http://localhost:8080
    herokuOAuthClientId: herokuOAuthClientId
    herokuOAuthClientSecret: herokuOAuthClientSecret
server:
  port: 8080
spring:
  profiles:
    include: common-dev
