codekvast:
  login:
    cipherSecret:                someCipherSecret
    herokuApiPassword:           herokuApiPassword
    herokuApiSsoSalt:            herokuApiSsoSalt
    herokuCodekvastUrl:          http://localhost:8080
    herokuOAuthClientId:         herokuOAuthClientId
    herokuOAuthClientSecret:     herokuOAuthClientSecret
spring:
  profiles:
    include: common-dev
server:
  port:                     8080
