#-------------------------------------------------------------------------------------------------------------------------------------------
# This file contains all properties that are NOT injected by Gradle. These go into application.properties, since Gradle's expand()
# does not play well with YAML.
#
# Spring Boot reads and merges both application.properties and application.yml.
#-------------------------------------------------------------------------------------------------------------------------------------------
codekvast:
  login:
    herokuApiBaseUrl:            https://api.heroku.com
    herokuOAuthBaseUrl:          https://id.heroku.com

management:
  endpoint:
    health:
      cache.time-to-live: 1s

server:
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 10m
      persistent: false
spring:
  application.name:    Codekvast Login
  http:
    converters.preferred-json-mapper: gson
    log-request-details:              true
  cache:
    caffeine:
      spec: 'expireAfterAccess=10m'
  profiles:
    include: common
  security.oauth2.client:
    registration:
      facebook:
        client-scope:  email
      github:
        client-scope:  email
      google:
        client-scope:  email
