#!/bin/bash
function modifyIpTables() {
    VERB=$1
    iptables -t nat $VERB PREROUTING -p tcp --dport 80 -i eth0 -j REDIRECT --to-port 8080
    iptables -t nat $VERB PREROUTING -p tcp --dport 443 -i eth0 -j REDIRECT --to-port 8443
    iptables -t nat $VERB OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 8080
    iptables -t nat $VERB OUTPUT -p tcp --dport 8443 -j REDIRECT --to-port 8443
}

case "$1" in
    start)
    modifyIpTables -A
    ;;

    stop)
    modifyIpTables -D
    ;;

    status)
    iptables -t nat -L
    ;;

    *)
    echo "Usage: $0 [start|stop|status]"
    exit 1
esac
