import io.codekvast.backoffice.facts.CollectionStarted
import io.codekvast.backoffice.facts.ContactDetails
import io.codekvast.common.messaging.model.CodekvastEvent
import io.codekvast.common.messaging.model.CollectionStartedEvent
import io.codekvast.backoffice.service.MailSender

global java.time.Clock clock
global Long customerId
global io.codekvast.backoffice.service.MailSender mailSender
global org.slf4j.Logger logger

rule "Register that collection has started"
when
  $cse: CollectionStartedEvent()
  not(CollectionStarted())
then
   insert(CollectionStarted.of($cse));
end

rule "Send welcome mail when collection has started"
when
  $cs: CollectionStarted(welcomeMailSent == false)
  $cd: ContactDetails()
then
  mailSender.sendMail(MailSender.Template.WELCOME_COLLECTION_HAS_STARTED, $cd.getContactEmail(), customerId);
  modify($cs) {
    setWelcomeMailSent(true)
  }
end
