= Codekvast User Manual
:author: Olle Hallin
:email: olle.hallin@crisp.se
:revnumber: {codekvastVersion}
:revdate: {gitTime}
:revremark: {gitId}
:imagesdir: images
:data-uri:
:numbered:
:linkattrs:
:toc: left
:toclevels: 3
:icons: font
:source-highlighter: prettify
:attribute-missing: warn
:description: Codekvast is a tool that detects Truly Dead Code in your Java app.
:aspectj-ltw-config: link:https://eclipse.org/aspectj/doc/next/devguide/ltw-configuration.html[AspectJ Load-Time Weaver configuration]
:overhead-nanoseconds: 20


Codekvast User Manual covers installation and usage of Codekvast, a tool for detecting Truly Dead Code in JVM-based applications.

[abstract]
== Abstract

Codekvast is a tool for detecting <<truly-dead-code, Truly Dead Code>>. By that we mean code that is in <<use-in-production,
production>> but not used by any real users for a <<usage-cycle, usage cycle>>.

Codekvast works for Java and other languages that execute in a JVM.

== Architecture
Codekvast consists of two parts: the *Agent* and the *Dashboard*.

.Responsibilities
Codekvast Agent:: The agent is attached to the JVM that runs your application. It makes an inventory of the <<code-base, code base>> and records the invocations of the methods of
interest. At the end of each recording interval, the <<invocation-data, invocation data>> is transferred to the dashboard, and a new recording
interval is started. The agent uses http://en.wikipedia.org/wiki/AspectJ[AspectJ, role="external", window="_new"]
for hooking into your application. *The agent requires Java 7 or higher.*

Codekvast Dashboard:: The dashboard receives code base and invocation publications from the agents, stores it in a database and makes it available for browsing and reporting
in a web interface. It also offers a REST interface to facilitate IDE plugin development. There is only one dashboard. *The dashboard requires Java 8 or higher plus MariaDB server 10 or higher*

---

[[architecture-diagram]]
[ditaa, "architecture-diagram"]
.Architecture Diagram
....
+---------------------------------------------------------------+
| Host_1                                                        |
|                                                               |
|   +--------------------------------+                          |
|   | JVM 1                          |                          |
|   | +---------------------+        |                          |
|   | | Your app            |        |                          |
|   | | cGRE                |        |       +----------------+ |
|   | +---------------------+        |       | codekvast.conf | |
|   |   ^              |             |       |                | |
|   |   |<-=- weaves   |<-=- invokes |   /-->| cYEL           | |
|   | +--------------+ |             |   |   | {d}            | |
|   | | aspectjweaver| |             |   |   +----------------+ |                       Legend:
|   | | c999         | |             |   |                      |
|   | +--------------+ |             |   |                      |                +----------------------+
|   |   ^              |             |   |<-=- reads            |                |Your application cGRE |
|   |   |<-=-embeds    v             |   |                      |                +----------------------+
|   | +---------------------+        |   |                      |
|   | | Codekvast agent     +------------/   /----------------\ |                +----------------------+
|   | | cYEL                +--------------->|app binaries    | |                |Part of Codekvast cYEL|
|   | +----+------+---------+        |   ^   |cGRE            | |                +----------------------+
|   |      |      |                  |   |   \----------------/ |
|   |      |      \--------------\   |   |                      |                +----------------------+
|   +------|---------------------|---+   \-=- makes inventory of|                |Part of AspectJ c999  |
|          |                     |                              |                +----------------------+
|          | <-=--produces----=->|                              |
|          |                     |                              |
|          v                     v                              |
|      +------------------+    +------------------+             |
|      | Code base        |    | Invocation data  |             |
|      | publications     |    | publications     |             |
|      |                  |    |                  |             |
|      | {d}              |    | {d}              |             |
|      +------------------+    +------------------+             |
|              |                         |                      |
+--------------|-------------------------|----------------------+
               |                         |
               |<-=--- HTTP POST -----=->|
               |                         |
               \-----\                   |
                     |                   |
                     v                   v
           +----------------------------------------+
           | Codekvast Dashboard                    |
           |                          /----------\  |
           | o Publication import     | MariaDB  |  |
           | o Persistence layer <--->| database |  |
           | o IDE API                |          |  |
           | o Reporting              |          |  |
           | o Web application        \----------/  |
           | cYEL                                   |
           +----------------------------------------+
                    ^                     ^
                    |<-=-- HTTP           |<-=-- REST
                    v                     v
               /---------------\     /---------------\
               | HTML5         |     | IDE           |
               | browser       |     |               |
               \---------------/     \---------------/
....

== Configuration

See http://www.codekvast.io

== Usage hints
[[use-in-production]]
Use Codekvast In Production:: Your _real users use your software in your production environment_. Period.
+
Therefore, you must collect usage data _where your real users use your software, i.e., in production!_
+
It is only in production you can get reliable data.
+
Of course you can use Codekvast during training or test, but you will probably find less <<truly-dead-code, truly dead code>>
than if you use Codekvast in production!
+
[NOTE]
====
The Codekvast Agent is extremely efficient. It adds roughly {overhead-nanoseconds} nanoseconds to each tracked method call.

The memory consumption is low. For a fairly large server application (0.5 million lines of code), the complete set of tracked
method names occupy less than 10 MB of heap space.

The collected data is written to a plain text file in the local file system at the end of each collection interval. This is also
very efficient.
====

[[always-on]]
Codekvast Should Be Always On:: To get reliable results, _Codekvast should be running all the time, on all the servers in your server farm._
+
If you break this rule, you will get misleading results, since individual servers in a cluster will have slightly different
work-load.
+
The results will be misleading in the sense that Codekvast might report perfectly healthy code as <<truly-dead-code,truly dead>>.

== Glossary

[[truly-dead-code]]
Truly Dead Code:: By Truly Dead Code we mean code that is _deployed in production, is available to users but has not been used for a certain
period of time_ (a <<usage-cycle, usage cycle>>).
+
Modern IDE:s like JetBrains IDEA can detect _statically_ dead code, but will never suggest removal of any public methods.
 The IDE cannot know who the clients to the public code are.
+
Statically dead code is code that the IDE can prove that no-one ever can invoke. The proof is done by analysing the source
   code.
+
By collecting runtime invocation data, Codekvast kan help identify truly dead code _without access to the source code_.
+
_Why is Truly Dead Code harmful?_
+
It is not harmful per se, since no-one is using it.
+
Nevertheless, it _is_ harmful in a more subtle sense:
+

* It is most likely the oldest code that is truly dead. The oldest code was probably written by less experienced developers,
    and probably is more http://williamdurand.fr/2013/07/30/from-stupid-to-solid-code[STUPID, role="external", window="_blank"]
    than http://www.codeproject.com/Articles/60845/The-S-O-L-I-D-Object-Oriented-Programming-OOP-Prin[SOLID, role="external", window="_blank"].

* Old code might contain undetected security vulnerabilities, since the code was written when the knowledge about e.g.,
https://www.owasp.org/index.php/Top_10_2013-Top_10[OWASP Top 10, role="external", window="_blank"] was not widespread.

* More code makes the code base harder to navigate and understand.
* More code slows down the development cycle. All code should be tested!
* Old code might hinder tool, libraries and framework upgrades. It is often the oldest code that use deprecated library
    features.

[[usage-cycle]]
Usage Cycle:: The period of time after one can assume that all features of an application has been used.
+
For some applications, the usage cycle could be a number of days.
+
For other applications, the usage cycle could be weeks, months or even years.
+
Only you can tell what the usage cycle is for your application. Usage cycle is not a fixed value. Once Codekvast has been running for a
while, you can experiment with different values of usage cycle.
+
Different applications that are parts of the same solution probably have different usage cycles. Example: front-end web, mobile API,
back-office web, data warehouse.

[[code-base]]
Code Base:: The the complete set of methods that exist in the application. It contains the fully qualified names of the methods and meta-data about if the method is recorded or not.

[[invocation-data]]
Invocation Data:: The set of methods that have been invoked during a collection interval. It contains the fully qualified names of the
methods and the fully qualified types of the methods`' parameters.

[[application-binaries]]
Application Binaries::
The WAR file, EAR file or set of JAR files that make up your application. Codekvast Daemon needs these in order to
make an inventory of the available methods in your application.

[[method-inventory]]
Method Inventory:: All methods which belong to any of the packages of interest.
