= Codekvast User Manual
:author: Olle Hallin
:email: olle.hallin@crisp.se
:revnumber: {codekvastVersion}
:revdate: {gitTime}
:revremark: {gitId}
:imagesdir: images
:data-uri:
:numbered:
:linkattrs:
:toc: left
:toclevels: 3
:icons: font
:source-highlighter: prettify
:attribute-missing: warn
:description: Codekvast is a tool that detects Truly Dead Code in your Java app.
:aspectj-ltw-config: link:https://eclipse.org/aspectj/doc/next/devguide/ltw-configuration.html[AspectJ Load-Time Weaver configuration]
:overhead-nanoseconds: 20


Codekvast User Manual covers installation and usage of Codekvast, a tool for detecting Truly Dead Code in JVM-based applications.

[abstract]
== Abstract

Codekvast is a tool for detecting <<truly-dead-code, Truly Dead Code>>. By that we mean code that is in <<use-in-production,
production>> but not used by any real users for a <<usage-cycle, usage cycle>>.

Codekvast works for Java and other languages that execute in a JVM.

== Architecture
Codekvast consists of two parts: the *Agent* and the *Warehouse*.

.Responsibilities
Codekvast Agent:: The agent is attached to the JVM that runs your application. It makes an inventory of the <<code-base, code base>> and records the invocations of the methods of
interest. At the end of each recording interval, the <<invocation-data, invocation data>> is transferred to the warehouse, and a new recording
interval is started. The agent uses http://en.wikipedia.org/wiki/AspectJ[AspectJ, role="external", window="_new"]
for hooking into your application. *The agent requires Java 7 or higher.*

Codekvast Warehouse:: The warehouse receives code base and invocation publications from the agents, stores it in a database and makes it available for browsing and reporting
in a web interface. It also offers a REST interface to facilitate IDE plugin development. There is only one warehouse. *The warehouse requires Java 8 or higher plus MariaDB server 10 or higher*

---

[[architecture-diagram]]
[ditaa, "architecture-diagram"]
.Architecture Diagram
....
+---------------------------------------------------------------+
| Host_1                                                        |
|                                                               |
|   +--------------------------------+                          |
|   | JVM 1                          |                          |
|   | +---------------------+        |                          |
|   | | Your app            |        |                          |
|   | | cGRE                |        |       +----------------+ |
|   | +---------------------+        |       | codekvast.conf | |
|   |   ^              |             |       |                | |
|   |   |<-=- weaves   |<-=- invokes |   /-->| cYEL           | |
|   | +--------------+ |             |   |   | {d}            | |
|   | | aspectjweaver| |             |   |   +----------------+ |                       Legend:
|   | | c999         | |             |   |                      |
|   | +--------------+ |             |   |                      |                +----------------------+
|   |   ^              |             |   |<-=- reads            |                |Your application cGRE |
|   |   |<-=-embeds    v             |   |                      |                +----------------------+
|   | +---------------------+        |   |                      |
|   | | Codekvast agent     +------------/   /----------------\ |                +----------------------+
|   | | cYEL                +--------------->|app binaries    | |                |Part of Codekvast cYEL|
|   | +----+------+---------+        |   ^   |cGRE            | |                +----------------------+
|   |      |      |                  |   |   \----------------/ |
|   |      |      \--------------\   |   |                      |                +----------------------+
|   +------|---------------------|---+   \-=- makes inventory of|                |Part of AspectJ c999  |
|          |                     |                              |                +----------------------+
|          | <-=--produces----=->|                              |
|          |                     |                              |
|          v                     v                              |
|      +------------------+    +------------------+             |
|      | Code base        |    | Invocation data  |             |
|      | publications     |    | publications     |             |
|      |                  |    |                  |             |
|      | {d}              |    | {d}              |             |
|      +------------------+    +------------------+             |
|              |                         |                      |
+--------------|-------------------------|----------------------+
               |                         |
               |<-=--- HTTP POST -----=->|
               |                         |
               \-----\                   |
                     |                   |
                     v                   v
           +----------------------------------------+
           | Codekvast Warehouse                    |
           |                          /----------\  |
           | o Publication import     | MariaDB  |  |
           | o Persistence layer <--->| database |  |
           | o IDE API                |          |  |
           | o Reporting              |          |  |
           | o Web application        \----------/  |
           | cYEL                                   |
           +----------------------------------------+
                    ^                     ^
                    |<-=-- HTTP           |<-=-- REST
                    v                     v
               /---------------\     /---------------\
               | HTML5         |     | IDE           |
               | browser       |     |               |
               \---------------/     \---------------/
....
== Installation

[[codekvast-warehouse-installation]]
=== Install Codekvast Warehouse

Codekvast Warehouse is distributed with Docker Compose executed from a shell script.

It works for Mac OS X and Linux. Windows is not supported.

. Make sure Docker Engine and Docker Compose are installed. See https://docs.docker.com/compose/install/
. Execute the following commands in a shell:

[source,bash,subs="attributes,verbatim"]
----
wget {bintrayDownloadPrefix}/codekvast-warehouse.sh
chmod +x codekvast-warehouse.sh
./codekvast-warehouse.sh up -d
----

The MariaDB database files will be located in `/var/lib/codekvast-database`.

The Codekvast Warehouse log files will be located in `/var/log/codekvast/`.

The Codekvast Warehouse will listen on port 8080.

=== Codekvast Agent

// TODO Document how to install the agent in Heroku.

To Be Completed.

////
Your application must be modified to attach the Codekvast Agent.

It means the following things:

- Download the agent installation package codekvast-agent-{{codekvastVersion}.zip
- Unzip it to some known location
- Create `codekvast.conf` and put it in a location where Codekvast Agent will find it.
- Modify your application's start script

[[install-agent-tomcat-linux]]
==== Tomcat (Linux)

[source,bash,subs="attributes,verbatim"]
----
cd path/to/tomcat # <1>
cp /opt/codekvast-daemon-{codekvastVersion}/codekvast.conf conf/ # <2>
cp /opt/codekvast-daemon-{codekvastVersion}/tomcat/setenv.sh bin/
mkdir endorsed
# Copy the java agents to endorsed/
----
<1> Substitute `path/to` with the actual path were Tomcat is installed.
<2> Edit `conf/codekvast.conf` to suit your needs. See <<configuring-codekvast-agent, Configuring Codekvast Agent>>.

==== Other applications

Use <<install-agent-tomcat-linux, the installation guide for Tomcat>> as a basis.
////

The goal is to make

`-javaagent:/path/to/codekvast-agent-{codekvastVersion}.jar`

appear as the first arguments to the `java` command and to put `codekvast.conf` to any of the locations that
Codekvast Agent expects it. See <<codekvast-agent-config-file-location, Configuring Codekvast Agent>>.

////
[TIP]
====
There is a helper script called `/opt/codekvast-daemon{codekvastVersion}/showJvmParams.sh` which produces a valid JAVA_OPTS that can be pasted
into your application's start script.
====
////

==== Trouble shooting

No data is uploaded to Codekvast Warehouse::
. set `aspectjOptions=-verbose -showWeaveInfo` in `codekvast.conf`
. restart your application
. Use the logging for determining the problem. See <<codekvast-agent-logging, Codekvast Agent Logging>>.

== Configuration

[[configuring-codekvast-agent]]
=== Codekvast Agent

[[codekvast-agent-logging]]
==== Logging

The Codekvast Agent uses java.util.logging as logging API.

Codekvast's loggers are prefixed with `io.codekvast.`.

[[codekvast-agent-config-file-location]]
==== Configuration File Name and Location

The Codekvast agent reads it's configuration from a file named `codekvast.conf` in any of these places (the
first found file will win):

. The Java system property `-Dcodekvast.configuration=path/to/configfile`.
. The environment variable `CODEKVAST_CONFIG=path/to/configfile`.
. It looks for `codekvast.conf` in
.. `.` (i.e., the working directory)
.. `./conf`
.. `${catalina.home}/conf` (catalina.home is a Java system property)
.. `$\{CATALINA_HOME}/conf` (CATALINA_HOME is an environment variable)
.. `${catalina.base}/conf` (catalina.base is a Java system property)
.. `$\{CATALINA_BASE}/conf` (CATALINA_BASE is an environment variable)
.. `$\{HOME}/.config` (HOME is an environment variable)
. It looks for codekvast.conf in `/etc/codekvast`.
. It looks for codekvast.conf in `/etc`.

==== Config file override mechanism
It is possible to override one or more parameters that were specified in the configuration file by defining the Java system property
`codekvast.options`. The value should be a semicolon-separated list of name=value pairs.

.Example
----
-Dcodekvast.options=appName=myApp;environment=staging
----

The override mechanism comes in handy when you want to use the same configuration files in many environments. Probably just the
environment name is different.

It is also possible to override any single parameter value by defining an environment variable with a name derived from the
parameter name: the environment variable `CODEKVAST_APP_NAME` will override the configuration file parameter `appName`,
 `CODEKVAST_ENVIRONMENT` will override `environment` and so on.

==== Codekvast Agent configuration file

The format of the file is a standard Java Properties file, that is, `key: value` or `key = value`. Long lines can be continued by ending the
line with a backslash ('\') and indenting the continuation line with at least one space.

The right-hand side may contain references to environment variables and Java system properties. Example:
....
codeBase = ${app.home}/lib
codeBase = $APP_HOME/lib
....

.Codekvast Agent parameters (mandatory parameters in *bold face*)
[cols="1,2,3,5,1", options="header"]
|===
|Parameter
|Description
|Format
|Example
|Default

|*codeBase*
|Where are my application binaries?
|A comma-separated list of file system paths. See <<about-specifying-code-base>>.
|codeBase = \ +
{nbsp}{nbsp}${catalina.home}/webapps/jenkins,\ +
{nbsp}{nbsp}${user.home}/.jenkins/plugins
|

|*appName*
|What is my application's name?
|A string.
|Jenkins
|

|appVersion
|What is my application's version?

Used for tracking dead code evolution.
|A string.

See <<about-app-version-strategy>>
|filename jenkins-core-(.*).jar
|unspecified

|*packages*
|What packages shall be tracked?
|A comma-separated list of strings.
|packages = com.acme, foo.bar
|

|excludePackages
|What packages shall *not* be tracked?
See <<about-exclude-package-prefixes>>.
|A comma-separated list of strings.
|excludePackages = com.acme.timecritical, foo.bar.even.more.time.critical
|

|environment
|In which environment is the application deployed?
|An arbitrary string, useful when analysing the collected data.
|environment = production
|

|methodVisibility
|Which methods should be tracked?
|One of the keywords *public*, *protected*, *package-private* or *private*.
See <<about-specifying-method-visibility>>.
|methodVisibility=protected
|protected

|aspectjOptions
|Should Codekvast Agent configure logging for Aspectj Weaver?
Useful for trouble shooting.
See also {aspectj-ltw-config}.
|A string.
|aspectjOptions = \ +
{nbsp}{nbsp}-verbose -showWeaveInfo
|

|bridgeAspectjMessagesToJUL
|Should aspectjweaver be configured with a bridge that sends AspectJ messages to java.util.logging (JUL)?
See <<about-bridgeAspectjMessages>>
|*true* or *false*.
|
|true

|serverUrl
|Where is the Codekvast Server?
|A HTTP or HTTPS URL
|http://codekvast.mycorp.com
|http://localhost:8080

|licenseKey
|What is my license key for authenticating to the Codekvast Server at?
|A string obtained when registering at XXX.
|
|

// TODO document licenseKey

|httpConnectTimeoutSeconds
|How long shall the agent wait for establishing a connection to the server?
|A positive integer denoting a number of seconds.
|
|10

|httpReadTimeoutSeconds
|How long shall the agent wait when reading a response from the server?
|A positive integer denoting a number of seconds.
|
|10

|httpWriteTimeoutSeconds
|How long may a request to the server take at most?
|A positive integer denoting a number of seconds.
|
|30

|httpProxyHost
|Do we need to call the Codekvast Server via an HTTP proxy such as Squid?
|hostname-or-IP-address
|10.57.0.10
|

|httpProxyPort
|Which port at the proxy should we connect to?
|A socket port number
|
|3128

|===

[[about-specifying-code-base]]
==== About specifying codeBase
For a WAR (e.g., jenkins.war) deployed in Tomcat, specify `/path/to/apache-tomcat-x.x.x/webapps/jenkins`
without the .war suffix. Tomcat will automatically explode the war into a folder without the .war suffix.

Some applications (e.g., Jenkins) will download plugins on the fly and store them in some well-known location on disk.
In the case of Jenkins this path is `${user.home}/.jenkins/plugins`.

Spaces in a path must be escaped, i.e., preceded with a backslash ('\') character.

When running on Windows, the colon after the drive letter must be escaped, i.e., preceded with a backslash '\'.

[[about-app-version-strategy]]
==== About specifying appVersion
Codekvast has some strategies for automatically finding the deployed application's version:

.Application version strategies
[cols="1,4,9,1"]
|===
|Strategy |Description |Examples |Result

|*manifest*
|Locates a certain jar file within the codeBase with a well-known name and extracts the version from the jar file's META-INF/MANIFEST.MF
|appVersion = manifest myapp.jar +
appVersion = manifest myapp.jar Implementation-Version +
appVersion = manifest myapp.jar My-Custom-Version-Attribute +

Example 1 and 2 yields the same result.
| The value of the manifest attribute

|*filename*
|Locates a jar file within the codeBase with a name that matches a regular expression and extracts the version from the part within parenthesis from
the file name.
|`appVersion = filename myapp-(.*).jar`
|The part within parenthesis.

|*literal*
|The value in the configuration file is used as-is.
|`literal 3.14`
|3.14

|===

[[about-exclude-package-prefixes]]
==== About excluding packages from collection
Codekvast Agent is extremely efficient, and each tracked method only incurs a runtime cost of approximately {overhead-nanoseconds} nanoseconds.
If you have code that execute in tight loops even this low overhead could be too much.

In such situations you can exclude code from Codekvast. See also <<about-specifying-method-visibility, Specifying Method Visibility>>

[[about-specifying-method-visibility]]
==== About specifying methodVisibility

There is a certain overhead associated with tracking method calls, both in terms of CPU cycles and memory consumption.
By specifying which methods shall be tracked, you can control the overhead.

[NOTE]
====
Modern IDEs like IntelliJ are capable of suggesting deletion of dead methods as long as the method visibility is package private or private.
They cannot suggest deletion of public or protected method is dead, since they cannot know what other clients to the method that exist.
====

.Method visibilities
[cols="1,9,1,1"]
|===
|Visibility |Result |Synonyms |Overhead

|*public* |Track public methods only. | |Lowest
|*protected* |Track public and protected methods. This is the default. | |Lower
|*package-private* |Track public, protected and package-private (default) methods. |*!private* |Higher
|*private* |Track all methods. |*all* |Highest

|===

[[about-bridgeAspectjMessages]]
==== About Bridging AspectJ messages to JUL
Normally, codekvast-agent installs an AspectJ `IMessageHandler` that acts as a bridge between aspectjweaver and java.util.logging (JUL).
If your application uses another implementation or if you want the default behaviour, this bridge can be disabled.

See also {aspectj-ltw-config} and <<codekvast-agent-logging, Codekvast Agent Logging>>.

[[configuring-codekvast-warehouse]]
=== Codekvast Warehouse
The warehouse reads it configuration from /opt/codekvast-warehouse-{codekvastVersion}/application.properties.

The file is self-documenting.

== Usage hints
[[use-in-production]]
Use Codekvast In Production:: Your _real users use your software in your production environment_. Period.
+
Therefore, you must collect usage data _where your real users use your software, i.e., in production!_
+
It is only in production you can get reliable data.
+
Of course you can use Codekvast during training or test, but you will probably find less <<truly-dead-code, truly dead code>>
than if you use Codekvast in production!
+
[NOTE]
====
The Codekvast Agent is extremely efficient. It adds roughly {overhead-nanoseconds} nanoseconds to each tracked method call.

The memory consumption is low. For a fairly large server application (0.5 million lines of code), the complete set of tracked
method names occupy less than 10 MB of heap space.

The collected data is written to a plain text file in the local file system at the end of each collection interval. This is also
very efficient.
====

[[always-on]]
Codekvast Should Be Always On:: To get reliable results, _Codekvast should be running all the time, on all the servers in your server farm._
+
If you break this rule, you will get misleading results, since individual servers in a cluster will have slightly different
work-load.
+
The results will be misleading in the sense that Codekvast might report perfectly healthy code as <<truly-dead-code,truly dead>>.

== Glossary

[[truly-dead-code]]
Truly Dead Code:: By Truly Dead Code we mean code that is _deployed in production, is available to users but has not been used for a certain
period of time_ (a <<usage-cycle, usage cycle>>).
+
Modern IDE:s like JetBrains IDEA can detect _statically_ dead code, but will never suggest removal of any public methods.
 The IDE cannot know who the clients to the public code are.
+
Statically dead code is code that the IDE can prove that no-one ever can invoke. The proof is done by analysing the source
   code.
+
By collecting runtime invocation data, Codekvast kan help identify truly dead code _without access to the source code_.
+
_Why is Truly Dead Code harmful?_
+
It is not harmful per se, since no-one is using it.
+
Nevertheless, it _is_ harmful in a more subtle sense:
+

* It is most likely the oldest code that is truly dead. The oldest code was probably written by less experienced developers,
    and probably is more http://williamdurand.fr/2013/07/30/from-stupid-to-solid-code[STUPID, role="external", window="_blank"]
    than http://www.codeproject.com/Articles/60845/The-S-O-L-I-D-Object-Oriented-Programming-OOP-Prin[SOLID, role="external", window="_blank"].

* Old code might contain undetected security vulnerabilities, since the code was written when the knowledge about e.g.,
https://www.owasp.org/index.php/Top_10_2013-Top_10[OWASP Top 10, role="external", window="_blank"] was not widespread.

* More code makes the code base harder to navigate and understand.
* More code slows down the development cycle. All code should be tested!
* Old code might hinder tool, libraries and framework upgrades. It is often the oldest code that use deprecated library
    features.

[[usage-cycle]]
Usage Cycle:: The period of time after one can assume that all features of an application has been used.
+
For some applications, the usage cycle could be a number of days.
+
For other applications, the usage cycle could be weeks, months or even years.
+
Only you can tell what the usage cycle is for your application. Usage cycle is not a fixed value. Once Codekvast has been running for a
while, you can experiment with different values of usage cycle.
+
Different applications that are parts of the same solution probably have different usage cycles. Example: front-end web, mobile API,
back-office web, data warehouse.

[[code-base]]
Code Base:: The the complete set of methods that exist in the application. It contains the fully qualified names of the methods and meta-data about if the method is recorded or not.

[[invocation-data]]
Invocation Data:: The set of methods that have been invoked during a collection interval. It contains the fully qualified names of the
methods and the fully qualified types of the methods`' parameters.

[[application-binaries]]
Application Binaries::
The WAR file, EAR file or set of JAR files that make up your application. Codekvast Daemon needs these in order to
make an inventory of the available methods in your application.

[[method-inventory]]
Method Inventory:: All methods which belong to any of the packages of interest.
