= Codekvast User Manual
:author: Olle Hallin
:email: olle.hallin@crisp.se
:revnumber: {codekvastVersion}
:revdate: {gitTime}
:revremark: {gitId}
:imagesdir: images
:data-uri:
:numbered:
:linkattrs:
:toc: left
:toclevels: 3
:icons: font
:source-highlighter: prettify
:attribute-missing: warn
:description: Codekvast is a tool that detects Truly Dead Code in your Java app.
:aspectj-ltw-config: link:https://eclipse.org/aspectj/doc/next/devguide/ltw-configuration.html[AspectJ Load-Time Weaver configuration]
:overhead-nanoseconds: 30


Codekvast User Manual covers installation and usage of Codekvast, a tool for detecting Truly Dead Code in JVM-based applications.

[abstract]
== Abstract

Codekvast is a tool for detecting <<truly-dead-code, Truly Dead Code>>. By that we mean code that is in <<use-in-production,
production>> but not used by any real users for a <<usage-cycle, usage cycle>>.

Codekvast works for Java and other languages that execute in a JVM.

== Architecture
Codekvast consists of three parts: the *Collector*, the *Daemon* and the *Warehouse*.

.Responsibilities
Codekvast Collector:: The collector is attached to the JVM that runs your application. It records the invocations of the methods of
interest. At the end of each recording interval, the <<invocation-data, invocation data>> is written to a text file, and a new recording
interval is started.
There is exactly one collector per JVM. The collector uses http://en.wikipedia.org/wiki/AspectJ[AspectJ, role="external", window="_new"]
for hooking into your application. *The collector requires Java 6 or higher.*

Codekvast Daemon:: Analyses the application's <<application-binaries, binaries>> to produce an <<method-inventory, inventory>> of the
application. The
inventory consists of all the method signatures that the collector potentially can record. The daemon combines the method inventory with the invocation data
 from the collector(s) and uploads it to the warehouse. There is one daemon per server host. One daemon can collect invocation data from
 several JVMs that are executing in the same host. *The daemon requires Java 8 or higher.*

Codekvast Warehouse:: Receives inventory and invocation data from the daemon(s), stores it in a database and makes it available for browsing
in a web interface. It also offers a REST interface to facilitate IDE plugin development. There is only one warehouse. *The warehouse requires Java 8 or higher plus MariaDB server 10 or higher*

[TIP]
====
Codekvast Warehouse including MariaDB is available as Docker images. See <<codekvast-warehouse-docker-installation, Codekvast Warehouse Docker Compose installation guide>>.
====

---

[[architecture-diagram]]
[ditaa, "architecture-diagram"]
.Architecture Diagram
....
+------------------------------------------------------------------------------+         +---------------------------+
| Host_1                                                                       |         | Host_n                    |
|                                                                              |         |                           |
|   +------------------------------+        +-------------------------+        |         |  +-=-----------------+    |
|   | JVM 1                        |        | JVM m                   |        |         |  | One or more JVMs  |    |
|   | +---------------------+      |        | +---------------------+ |        |         |  |                   |    |
|   | | Your app_1          |      |        | | Your app_m          | |        |         |  |                   |    |
|   | | cGRE                |      |        | | cGRE                | |        |         |  |                   |    |
|   | +---------------------+      |        | +---------------------+ |        |         |  |                   |    |
|   |   ^              |           |        |                         |        |         |  |                   |    |
|   |   |<-=weaves     |<-=invokes |        |                         |        |         |  |                   |    |
|   | +--------------+ |           |        | +---------------------+ |        |         |  |                   |    |
|   | | aspectjweaver| |           |        | | aspectjweaver       | |        |         |  |                   |    |
|   | | c999         | |           |-=----  | | c999                | |        |         |  |                   |    |
|   | +--------------+ |           |        | +---------------------+ |        |         |  |                   |    |
|   |   ^              |           |        |                         |        |         |  |                   |    |
|   |   |<-=instructs  v           |        |                         |        |  -=---- |  |                   |    |
|   | +---------------------+      |        | +---------------------+ |        |         |  |                   |    |
|   | | Codekvast collector |      |        | | Codekvast collector | |        |         |  |                   |    |
|   | | cYEL                |      |        | | cYEL                | |        |         |  |                   |    |
|   | +----+------+---------+      |        | +----+---------+------+ |        |         |  |                   |    |
|   |      |      |                |        |      |         |        |        |         |  |         |         |    |
|   |      |      \--------------\ |        |  /---/         |        |        |         |  |         |         |    |
|   +------|---------------------|-+        +--|-------------|--------+        |         |  +---------|---------+    |
|          |                     |             |             |                 |         |            |              |
|          | <-=--produces       |<-=-reads-=->|             |                 |         |            |              |
|          V                     v             v             V                 |         |            V              |
|       +------------------+   +-----------------+   +------------------+      |         |    +-=---------------+    |
|       | Invocation data  |   | codekvast.conf  |   | Invocation data  |      |         |    | Invocation data |    |
|       | files            |   | cYEL            |   | files            |      |         |    | files           |    |
|       |                  |   |                 |   |                  |      |         |    |                 |    |
|       | {d}              |   | {d}             |   | {d}              |      |         |    | {d}             |    |
|       +------------------+   +-----------------+   +------------------+      |         |    +-----------------+    |
|                ^                                            ^                |         |            ^              |
|                | <-=-------------consumes----------------=->|                |         |            |              |
|                \------------\       /-----------------------/                |         |            |              |
|                             |       |                                        |         |            |              |
|                             |       |               /-=--loads classes from  |         |            |              |
|                     +-------+-------+------------+  |  /------------------\  |         |  +-=-------+----------+   |
|                     | Codekvast daemon 1         |  v  |app_1 binaries    |  |         |  | Codekvast daemon n |   |
|                     | cYEL                       |---->|cGRE              |  |         |  | cYEL               |   |
|                     |                            |--\  \------------------/  |         |  |                    |   |
|                     |                            |  |          :             |         |  |                    |   |
|                     +---+------------------------+  |          |             |         |  +-----+--------------+   |
|                         |<-=produces                |  /------------------\  |         |        |                  |
|                         v                           |  |app_m binaries    |  |         |        v                  |
|                     +------------+                  \->|cGRE              |  |         |  +-=----------+           |
|                     | aggregated |                     \------------------/  |         |  | aggregated |           |
|                     | data (zip) |                                           |         |  | data (zip) |           |
|                     | {d}        |                                           |         |  | {d}        |           |
|                     +---+--------+                                           |         |  +--+---------+           |
|                         |                                                    |         |     :                     |
+-------------------------|----------------------------------------------------+         +-----|---------------------+
                          |                                                                    |
                          |<-=--------------------File transfer-----------------------------=->|
                          |                                                                    |
                          \----------------\                                /------------------/
                                           |                                |
                                           v                                v
                                       +----------------------------------------+
                                       | Codekvast Warehouse                    |
                                       |                          /----------\  |
                                       | o File import            | MariaDB  |  |
                                       | o Persistence layer <--->| database |  |
                                       | o IDE API                |          |  |
                                       | o Reporting              |          |  |
                                       |                          \----------/  |
                                       | cYEL                                   |
                                       +----------------------------------------+
                                                ^                     ^
                                                |<-=-- HTTP           |<-=-- REST
                                                v                     v
                                           /---------------\     /---------------\
                                           | HTML5         |     | IDE           |
                                           | browser       |     |               |
                                           \---------------/     \---------------/

            +---------------------+   +----------------------+    +--------------------+
 Legend:    |Your application cGRE|   |Part of Codekvast cYEL|    |Part of AspectJ c999|
            +---------------------+   +----------------------+    +--------------------+
....
== Installation
=== Install Codekvast Daemon

The Codekvast daemon must be installed in each host that runs an application that shall be tracked by Codekvast.

You have two options here:

. Let http://www.ansible.com/[Ansible] do it for you, all hosts at once.
. Do it manually, host by host

==== The Ansible way
Execute the following commands in a shell:

[source,bash,subs="attributes,verbatim"]
----
apt-get install ansible # <1>
wget {bintrayDownloadPrefix}/codekvast-ansible-{codekvastVersion}.zip
unzip codekvast-ansible-{codekvastVersion}.zip
cd codekvast-ansible-{codekvastVersion}
----
<1> This works for Debian-based distros. For Redhat, use `yum install ansible` instead.

Now, edit `codekvast-daemon.yml` and `inventory` to suit your needs.

Finally, let Ansible to the heavy lifting of installing and configuring Codekvast Daemon in the hosts in `inventory`:

[source,bash,subs="attributes,verbatim"]
----
ansible-playbook -i inventory codekvast-daemon.yml
----

If you have configured `codekvast_warehouse` in `codekvast-daemon.yml`, you must make sure that the hosts can connect without
username and password. See <<configuring-scp-to-codekvast-warehouse>>.

==== Manual installation
Execute the following commands in a shell:

[source,bash,subs="attributes,verbatim"]
----
RUN_DAEMON_AS_USER=root # <1>
sudo /etc/init.d/codekvast-daemon stop # <2>
sudo wget {bintrayDownloadPrefix}/codekvast-daemon-{codekvastVersion}.zip
sudo unzip codekvast-daemon-{codekvastVersion}.zip -d /opt
sudo chown $RUN_DAEMON_AS_USER /opt/codekvast-daemon-{codekvastVersion}/codekvast-daemon.jar # <1>
sudo rm -f /etc/init.d/codekvast-daemon # <2>
sudo ln -s /opt/codekvast-daemon-{codekvastVersion}/codekvast-daemon.jar /etc/init.d/codekvast-daemon # <3>
sudo update-rc.d codekvast-daemon defaults # <4>
sudo vi /opt/codekvast-daemon-{codekvastVersion}/application.properties # <5>
----
<1> Insert the name of the user that runs your application(s) here. Codekvast Daemon needs permission to delete consumed
collection data files. You can also assign proper owner and/or permissions to /tmp/codekvast/.collector/ so that codekvast-daemon can remove
collector data files created by your application(s). See `man chmod` and `man chown`.
The daemon will run with the same user as the owner of the application jar file.
<2> In case you are upgrading from a previous version
<3> This works for  Linux distros that support System-V.
<4> This works for Debian-based distros. For Redhat, use `chkconfig --add codekvast-daemon` instead.
<5> Configure the daemon to suit your needs.

If you have configured `uploadToHost` in `/opt/codekvast-daemon-{codekvastVersion}/application.properties` you also need
to make sure that SCP works without asking for a password. See <<configuring-scp-to-codekvast-warehouse>>.

[[configuring-scp-to-codekvast-warehouse]]
=== Configuring automatic upload to Codekvast Warehouse
If you want Codekvast Daemon to upload collection data automatically to Codekvast Warehouse you must make sure
that the Codekvast Daemons can connect with ssh and scp to Codekvast Warehouse without having to provide a username and password.

This is done by creating and uploading a public key from each Codekvast Daemon server to the Codekvast Warehouse server.

For each Codekvast Daemon server, enter the following commands with the same user as the owner of `/opt/codekvast-daemon-{codekvastVersion}/codekvast-daemon.jar`:

[source,bash,subs="attributes,verbatim"]
----
SCP_TARGET=$( grep uploadToHost /opt/codekvast-daemon-{codekvastVersion}/application.properties | cut -d= -f2- ) # <1>
ssh-keygen # <2>
ssh-copy-id $SCP_TARGET # <3>
----
<1> Extract the value of the uploadToHost parameter
<2> Generate a SSH key pair
<3> Upload the public key to the target server. You will have to enter your password in the target server here.

Once you have uploaded the public SSH key to the Codekvast Warehouse host, test that it works (still being the user that owns
`codekvast-daemon.jar`):

[source,bash,subs="attributes,verbatim"]
----
ssh $SCP_TARGET # <1>
exit # <2>
----
<1> You should be logged in without password
<2> Exit from the target server

Finally, restart Codekvast Daemon and check that it works:

[source,bash,subs="attributes,verbatim"]
----
sudo /etc/init.d/codekvast-daemon restart
----

Check that automatic upload is correctly configured by issuing

[source,bash,subs="attributes,verbatim"]
----
sudo tail -f /var/log/codekvast-daemon.log
----

After 10-15 seconds there will be an INFO logging containing the words "Will upload to".

=== Modify your applications`' start scripts

[[install-collector-tomcat-linux]]
==== Tomcat (Linux)

[source,bash,subs="attributes,verbatim"]
----
cd path/to/tomcat # <1>
cp /opt/codekvast-daemon-{codekvastVersion}/codekvast-collector.conf conf/ # <2>
cp /opt/codekvast-daemon-{codekvastVersion}/tomcat/setenv.sh bin/
----
<1> Substitute `path/to` with the actual path were Tomcat is installed.
<2> Edit `conf/codekvast-collector.conf` to suit your needs. See <<configuring-codekvast-collector, Configuring Codekvast Collector>>.

==== Tomcat (Windows)

[source,cmd,subs="attributes,verbatim"]
----
set CODEKVAST_HOME="path\to\codekvast-daemon-{codekvastVersion}" # <1>
cd path\to\tomcat # <2>
mkdir endorsed
copy %CODEKVAST_HOME%\javaagents\* endorsed
copy %CODEKVAST_HOME%\tomcat\setenv.bat bin\ # <3>
copy %CODEKVAST_HOME%\codekvast-collector.conf conf\ # <4>
----
<1> Substitute `path\to` with the actual path were Codekvast is installed.
<2> Substitute `path\to` with the actual path were Tomcat is installed.
<3> Edit `bin\setenv.bat` so that CODEKVAST_HOME matches the path were codekvast-daemon-{codekvastVersion} is installed.
<4> Edit `conf\codekvast-collector.conf` to suit your needs. See <<configuring-codekvast-collector, Configuring Codekvast Collector>>.

==== Other applications

Use <<install-collector-tomcat-linux, the installation guide for Tomcat>> as a basis.

The goal is to make

`-javaagent:/path/to/codekvast-collector-{codekvastVersion}.jar -javaagent:/path/to/aspectjweaver-{aspectjVersion}.jar`

appear as the first arguments to the `java` command and `codekvast-collector.conf` or `codekvast.conf` appear in any of the locations that
Codekvast Collector expects it. See <<codekvast-collector-config-file-location, Configuring Codekvast Collector>>.

[TIP]
====
There is a helper script called `/opt/codekvast-daemon{codekvastVersion}/showJvmParams.sh` which produces a valid JAVA_OPTS that can be pasted
into your application's start script.
====

==== Trouble shooting

If you get `LinkageError` on some aspectj-related type::
. Move `aspectjweaver-{aspectjVersion}.jar` to a separate directory (called `/path/to/endorsed` below).
. Add `-Djava.endorsed.dir=/path/to/endorsed/` to the `java` command.

No data in /tmp/codekvast::
. `export CODEKVAST_OPTIONS=verbose=true`
. set `aspectjOptions=-verbose -showWeaveInfo` in codekvast-collector.conf
. restart your application
. Use the logging on standard output and standard error for determining the problem

[[codekvast-warehouse-installation]]
=== Install Codekvast Warehouse
[[codekvast-warehouse-docker-installation]]
==== The Docker way

This works for Mac OS X and Linux. Windows is not supported.

. Make sure Docker Engine and Docker Compose are installed. See https://docs.docker.com/compose/install/
. Execute the following commands in a shell:

[source,bash,subs="attributes,verbatim"]
----
wget {bintrayDownloadPrefix}/docker-compose.yml
docker-compose -p codekvast up -d
----

The MariaDB database files will be located in `/var/lib/codekvast-database`.

The Codekvast Warehouse log files will be located in `/var/log/codekvast/`.

Codekvast Warehouse will look for import files in `/tmp/codekvast/.import`.

[[codekvast-warehouse-conventional-installation]]
==== Manual installation

. Make sure Java 8 or higher is installed.
. Make sure MariaDB server 10 or higher is installed.
. Execute the following commands in a shell:

[source,bash,subs="attributes,verbatim"]
----
sudo adduser codekvast # <1>
sudo mysql << EOF  # <2>
create database if not exists codekvast_warehouse;
grant all on codekvast_warehouse.* to 'codekvast'@'localhost' identified by 'codekvast';
EOF
sudo wget {bintrayDownloadPrefix}/codekvast-warehouse-{codekvastVersion}.zip
sudo unzip codekvast-warehouse-{codekvastVersion}.zip -d /opt
sudo chown codekvast:codekvast /opt/codekvast-warehouse-{codekvastVersion}/codekvast-warehouse.jar # <1>
sudo rm -f /etc/init.d/codekvast-warehouse
sudo ln -s /opt/codekvast-warehouse-{codekvastVersion}/codekvast-warehouse.jar /etc/init.d/codekvast-warehouse # <3>
sudo update-rc.d codekvast-warehouse defaults # <4>
sudo vi /opt/codekvast-warehouse-{codekvastVersion}/application.properties # <5>
----
<1> The service will run with the same user as the owner of the application jar file.
<2> You might need to add the options -u<username> and -p<password> to the mysql command.
<3> This works for Linux distros that support System-V.
<4> This works for Debian based distros. For Redhat, use `chkconfig --add codekvast-warehouse` instead.
<5> Edit application.properties to suit your needs. See <<configuring-codekvast-warehouse, Configuring Codekvast Warehouse>>.

Once you have finished editing application.properties, execute

----
sudo /etc/init.d/codekvast-warehouse start
----

Check that it starts correctly by issuing
----
sudo tail -f /var/log/codekvast-warehouse.log
----

== Configuration

[[configuring-codekvast-collector]]
=== Codekvast Collector

[[codekvast-collector-config-file-location]]
==== Configuration File Name and Location

The collector reads it's configuration from a file named either `codekvast-collector.conf` or `codekvast.conf` in any of these places (the
first found file will win)

. The Java system property `-Dcodekvast.configuration=path/to/configfile`.
. The environment variable `CODEKVAST_CONFIG=path/to/configfile`.
. The file `${codekvast.home}/codekvast-collector.conf` or `${codekvast.home}/codekvast.conf` (codekvast.home is a Java system property)
. The file `${codekvast.home}/conf/codekvast-collector.conf` or `${codekvast.home}/conf/codekvast.conf` (codekvast.home is a Java system property)
. The file `$\{CODEKVAST_HOME}/codekvast-collector.conf` or `$\{CODEKVAST_HOME}/codekvast.conf` (CODEKVAST_HOME is an environment variable)
. The file `$\{CODEKVAST_HOME}/conf/codekvast-collector.conf` or `$\{CODEKVAST_HOME}/conf/codekvast.conf` (CODEKVAST_HOME is an environment variable)
. In a similar way it looks for
.. ${catalina.home}/conf
.. $\{CATALINA_HOME}/conf
.. ${catalina.base}/conf
.. $\{CATALINA_BASE}/conf
. It looks for codekvast-collector.conf and codekvast.conf in the `conf/` sibling directory to where codekvast-collector-{codekvastVersion}.jar is located.
. It looks for codekvast-collector.conf and codekvast.conf in `/etc/codekvast`.
. It looks for codekvast-collector.conf and codekvast.conf in `/etc`.

[TIP]
====
To aid in troubleshooting configuration file location problems one can do `export CODEKVAST_VERBOSE=true` before starting the application.

This is handy since it can be done without editing any start scripts.
====

==== Config file override mechanism
It is possible to override one or more parameters that were specified in the configuration file by defining the Java system property
`codekvast.options`. The value should be a semicolon-separated list of name=value pairs.

.Example
----
-Dcodekvast.options=appName=myApp;collectorIntervalSeconds=600
----

The override mechanism comes in handy when you have more than one app in the same host, with mostly identical configuration. Probably
just the application name is different.

==== Codekvast Collector configuration file

The format of the file is a standard Java Properties file, that is, `key: value` or `key = value`. Long lines can be continued by ending the
line with a backslash ('\') and indenting the continuation line with at least one space.

The right-hand side may contain references to environment variables and Java system properties. Example:
....
dataDir = ${user.home}/codekvast
dataDir = $HOME/codekvast
....

.Codekvast Collector parameters (mandatory parameters in *bold face*)
[cols="1,2,3,5,1", options="header"]
|===
|Parameter
|Description
|Format
|Example
|Default

|*codeBase*
|Where are my application binaries?
|A comma-separated list of file system paths. See <<about-specifying-code-base>>.
|codeBase = \ +
{nbsp}{nbsp}${catalina.home}/webapps/jenkins,\ +
{nbsp}{nbsp}${user.home}/.jenkins/plugins
|

|*appName*
|What is my application's name?
|A string.
|Jenkins
|

|appVersion
|What is my application's version?

Used for tracking dead code evolution.
|A string.

See <<about-app-version-strategy>>
|filename jenkins-core-(.*).jar
|unspecified

|*packages*
|What packages shall be tracked?
|A comma-separated list of strings.
|packages = com.acme, foo.bar
|

|excludePackages
|What packages shall *not* be tracked?
See <<about-exclude-package-prefixes>>.
|A comma-separated list of strings.
|excludePackages = com.acme.timecritical, foo.bar.even.more.time.critical
|

|methodVisibility
|Which methods should be tracked?
|One of the keywords *public*, *protected*, *package-private* or *private*.
See <<about-specifying-method-visibility>>.
|methodVisibility=protected
|protected

|collectorResolutionSeconds
|Controls how often invocation data is exported from the Codekvast collector.
A higher value means less CPU overhead but higher memory demand.
A higher value also means less precision.
| A positive integer.
| collectorResolutionSeconds=3600
| 600

|dataPath
|Which part of the file system shall Codekvast Collector dump the invocation data to?
|A file system path.
|dataPath=/var/lib/codekvast/data
|/tmp/codekvast/.collector

|verbose
|Should Codekvast Collector say something on standard output upon start? Useful for trouble shooting.
|*true* or *false*.
|verbose=true
|false

|aspectjOptions
|Should Codekvast Collector configure logging for Aspectj Weaver?
Useful for trouble shooting.
See also {aspectj-ltw-config}.
|A string.
|aspectjOptions = \ +
{nbsp}{nbsp}-verbose -showWeaveInfo
|

|clobberAopXml
|Should $dataPath/$appName/aop.xml be overwritten when collector is restarted?
See <<about-clobberAopXml>>
|*true* or *false*.
|
|true

|===

[[about-specifying-code-base]]
==== About specifying codeBase
For a WAR (e.g., jenkins.war) deployed in Tomcat, specify `/path/to/apache-tomcat-x.x.x/webapps/jenkins`
without the .war suffix. Tomcat will automatically explode the war into a folder without the .war suffix.

Some applications (e.g., Jenkins) will download plugins on the fly and store them in some well-known location on disk.
In the case of Jenkins this path is `${user.home}/.jenkins/plugins`.

Spaces in a path must be escaped, i.e., preceded with a backslash ('\') character.

When running on Windows, the colon after the drive letter must be escaped, i.e., preceded with a backslash '\'.

[[about-app-version-strategy]]
==== About specifying appVersion
Codekvast has some strategies for automatically finding the deployed application's version:

.Application version strategies
[cols="1,4,9,1"]
|===
|Strategy |Description |Examples |Result

|*manifest*
|Locates a certain jar file within the codeBase with a well-known name and extracts the version from the jar file's META-INF/MANIFEST.MF
|appVersion = manifest myapp.jar +
appVersion = manifest myapp.jar Implementation-Version +
appVersion = manifest myapp.jar My-Custom-Version-Attribute +

Example 1 and 2 yields the same result.
| The value of the manifest attribute

|*filename*
|Locates a jar file within the codeBase with a name that matches a regular expression and extracts the version from the part within parenthesis from
the file name.
|`appVersion = filename myapp-(.*).jar`
|The part within parenthesis.

|*literal*
|The value in the configuration file is used as-is.
|`literal 3.14`
|3.14

|===

[[about-exclude-package-prefixes]]
==== About excluding packages from collection
Codekvast Collector is extremely efficient, and each tracked method only incurs a runtime cost of approximately {overhead-nanoseconds} nanoseconds.
If you have code that execute in tight loops even this low overhead could be too much.

In such situations you can exclude code from Codekvast. See also <<about-specifying-method-visibility, Specifying Method Visibility>>

[[about-specifying-method-visibility]]
==== About specifying methodVisibility

There is a certain overhead associated with tracking method calls, both in terms of CPU cycles and memory consumption.
By specifying which methods shall be tracked, you can control the overhead.

[NOTE]
====
Modern IDEs like IntelliJ are capable of suggesting deletion of dead methods as long as the method visibility is package private or private.
They cannot know if a public or protected method is dead, since they cannot know what other clients to the method that exist.
====

.Method visibilities
[cols="1,9,1,1"]
|===
|Visibility |Result |Synonyms |Overhead

|*public* |Track public methods only. | |Lowest
|*protected* |Track public and protected methods. This is the default. | |Lower
|*package-private* |Track public, protected and package-private (default) methods. |*!private* |Higher
|*private* |Track all methods. |*all* |Highest

|===

[[about-clobberAopXml]]
==== About clobberAopXml
Normally, codekvast-collector uses the information in codekvast.conf for producing a tailored aop.xml that then is fed to
aspectjweaver. This is done every time the instrumented application starts.

If you have special needs, you can disable this behaviour by setting `clobberAopXml = false`.

This gives you a chance to fine-tune how the AspectJ weaver shall work.

See {aspectj-ltw-config}.

[[configuring-codekvast-daemon]]
=== Codekvast Daemon
The daemon reads it configuration from /opt/codekvast-daemon-{codekvastVersion}/application.properties.

The file is self-documenting.

[[configuring-codekvast-warehouse]]
=== Codekvast Warehouse
The warehouse reads it configuration from /opt/codekvast-warehouse-{codekvastVersion}/application.properties.

The file is self-documenting.

== Usage hints
[[use-in-production]]
Use Codekvast In Production:: Your _real users use your software in your production environment_. Period.
+
Therefore, you must collect usage data _where your real users use your software, i.e., in production!_
+
It is only in production you can get reliable data.
+
Of course you can use Codekvast during training or test, but you will probably find less <<truly-dead-code, truly dead code>>
than if you use Codekvast in production!
+
[NOTE]
====
The Codekvast Collector is extremely efficient. It adds roughly {overhead-nanoseconds} nanoseconds to each tracked method call.

The memory consumption is low. For a fairly large server application (0.5 million lines of code), the complete set of tracked
method names occupy less than 10 MB of heap space.

The collected data is written to a plain text file in the local file system at the end of each collection interval. This is also
very efficient.
====

[[always-on]]
Codekvast Should Be Always On:: To get reliable results, _Codekvast should be running all the time, on all the servers in your server farm._
+
If you break this rule, you will get misleading results, since individual servers in a cluster will have slightly different
work-load.
+
The results will be misleading in the sense that Codekvast might report perfectly healthy code as <<truly-dead-code,truly dead>>.

== Glossary

[[truly-dead-code]]
Truly Dead Code:: By Truly Dead Code we mean code that is _deployed in production, is available to users but has not been used for a certain
period of time_ (a <<usage-cycle, usage cycle>>).
+
Modern IDE:s like JetBrains IDEA can detect _statically_ dead code, but will never suggest removal of any public methods.
 The IDE cannot know who the clients to the public code are.
+
Statically dead code is code that the IDE can prove that no-one ever can invoke. The proof is done by analysing the source
   code.
+
By collecting runtime invocation data, Codekvast kan help identify truly dead code _without access to the source code_.
+
_Why is Truly Dead Code harmful?_
+
It is not harmful per se, since no-one is using it.
+
Nevertheless, it _is_ harmful in a more subtle sense:
+

* It is most likely the oldest code that is truly dead. The oldest code was probably written by less experienced developers,
    and probably is more http://williamdurand.fr/2013/07/30/from-stupid-to-solid-code[STUPID, role="external", window="_blank"]
    than http://www.codeproject.com/Articles/60845/The-S-O-L-I-D-Object-Oriented-Programming-OOP-Prin[SOLID, role="external", window="_blank"].

* Old code might contain undetected security vulnerabilities, since the code was written when the knowledge about e.g.,
https://www.owasp.org/index.php/Top_10_2013-Top_10[OWASP Top 10, role="external", window="_blank"] was not widespread.

* More code makes the code base harder to navigate and understand.
* More code slows down the development cycle. All code should be tested!
* Old code might hinder tool, libraries and framework upgrades. It is often the oldest code that use deprecated library
    features.

[[usage-cycle]]
Usage Cycle:: The period of time after one can assume that all features of an application has been used.
+
For some applications, the usage cycle could be a number of days.
+
For other applications, the usage cycle could be weeks, months or even years.
+
Only you can tell what the usage cycle is for your application. Usage cycle is not a fixed value. Once Codekvast has been running for a
while, you can experiment with different values of usage cycle.
+
Different applications that are parts of the same solution probably have different usage cycles. Example: front-end web, mobile API,
back-office web, data warehouse.

[[invocation-data]]
Invocation Data:: The set of methods that have been invoked during a collection interval. It contains the fully qualified names of the
methods and the fully qualified types of the methods`' parameters.

[[application-binaries]]
Application Binaries::
The WAR file, EAR file or set of JAR files that make up your application. Codekvast Daemon needs these in order to
make an inventory of the available methods in your application.

[[method-inventory]]
Method Inventory:: All methods which belong to any of the packages of interest.
