---
-   hosts: all
    connection: local
    become: no

    vars:
        defaultJavaVersion: "{{ lookup('ini', 'sdkmanJavaDefault type=properties file=../../../gradle.properties') }}"

    pre_tasks:
        - name: Extract Java versions to install from <rootDir>/gradle.properties
          shell: grep sdkmanJavaVersion_ ../../../gradle.properties | awk '{print $3}'
          register: javaVersions

        - set_fact:
            packages: "{{ packages|default([]) + [{'candidate': 'java', 'version': item }] }}"
          with_items: "{{ javaVersions.stdout_lines }}"

    roles:
    -   role: comcast.sdkman
        sdkman_install_packages: "{{ packages }}"
        sdkman_defaults:
            java: "{{ defaultJavaVersion }}"
        tags:
        - compilers
        - sdkman
