---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Database, which is served by MariaDB
#-----------------------------------------------------------------------------------------------------------
- name: Codevast Database Server
  hosts: tag_role_database
  user: ubuntu
  become: yes

  vars_files:
  - vars/secrets.yml
  - vars/common.yml

  vars:
    mysql_origin: 'default'
    mysql_vendor: 'mariadb'
    mariadb_version: '10.1'
    mysql_backup_dir: '/var/backups/mariadb'
    mysql_bind_address: '0.0.0.0'
    mysql_extra_configuration:
      character_set_server: 'utf8'
      collation_server: 'utf8_general_ci'

    mysql_databases:
    - codekvast

    mysql_users:
    - name: 'codekvast'
      password: '{{ mysql_application_password }}'
      priv: codekvast.*:ALL
      host: '%'

  roles:
  - {role: HanXHX.mysql, tags: mariadb}

  post_tasks:
  - set_fact:
      customer: "{{ hostvars[inventory_hostname]['ec2_tag_Customer'] }}"
      env: "{{ hostvars[inventory_hostname]['ec2_tag_Env'] }}"
      s3_bucket_location: "{{ hostvars[inventory_hostname]['ec2_region'] }}"

  - set_fact:
      s3_database_backup_bucket: "io.codekvast.{{ customer|lower }}.{{ env|lower }}.backup"

  - debug: var=s3_database_backup_bucket

  - name: Install s3cmd
    package: name=s3cmd state=installed

  - name: Install backup scripts
    template: src=database/{{ item }}.j2 dest=/root/{{ item }} mode=755
    with_items:
    - mariadb-backup
    - mariadb-restore
    - s3cfg

  - name: Check S3 access credentials
    shell: s3cmd --config=/root/s3cfg ls s3://{{ s3_database_backup_bucket }}
    changed_when: False

  - name: Link /root/mariadb-backup to /etc/cron.daily
    file: src=/root/mariadb-backup dest=/etc/cron.daily/mariadb-backup state=link
