# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/xenial64'
    config.vm.box_check_update = false

    # config.vm.network 'forwarded_port', guest: 8080, host: 8080
    # config.vm.network 'forwarded_port', guest: 80, host: 80
    config.vm.network 'private_network', ip: '192.168.33.10'
    # config.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"

    config.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.linked_clone = true
    end

    config.vm.provision :shell, inline: <<-EOF
      apt install -y python-minimal
    EOF

    config.vm.provision :ansible do |ansible|
        ansible.playbook = 'playbook.yml'
        ansible.raw_arguments = [
            '-e vagrantMode=true',
            '-e codekvast_herokuApiPassword=herokuApiPassword',
            '-e codekvast_herokuApiSsoSalt=herokuApiSsoSalt',
            '-e codekvast_webappJwtSecret=webappJwtSecret',
            '-e codekvast_queue_pollIntervalSeconds=5',
            '-e codekvast_webapp_jwtExpirationHours=-5',
            '-e codekvast_server_name=192.168.33.10'
        ]
    end
end
