### Dashboard 0
POST http://{{server0}}.codekvast.io:9081/management/lbhealth
Content-Type: application/json

### Dashboard 1
POST http://{{server1}}.codekvast.io:9081/management/lbhealth
Content-Type: application/json

###
