### Login 0
POST http://{{server0}}.codekvast.io:9080/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

### Login 1
POST http://{{server1}}.codekvast.io:9080/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

### Dashboard 0
POST http://{{server0}}.codekvast.io:9081/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

### Dashboard 1
POST http://{{server1}}.codekvast.io:9081/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

### Backoffice 0
POST http://{{server0}}.codekvast.io:9082/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

### Backoffice 1
POST http://{{server1}}.codekvast.io:9082/management/loggers/io.codekvast
Content-Type: application/json

{
    "configuredLevel": "INFO"
}

###
