---
- name: Create Datadog config directory for Codekvast
  file: path=/etc/datadog-agent/conf.d/codekvast.d state=directory
  tags: datadog

- name: Copy config fragments to Datadog config directory
  template: src=datadog/{{ item.src }} dest=/etc/datadog-agent/conf.d/codekvast.d/{{ item.dest }}
  with_items:
  - src: 0-logs.fragment.yml
    dest: 0-logs.fragment
  - src: service.fragment.yml
    dest: "{{ service_name }}.fragment"
  tags: datadog

- name: Assemble the Datadog config file
  assemble:
    src: /etc/datadog-agent/conf.d/codekvast.d/
    regexp: "\\.fragment$"
    dest: /etc/datadog-agent/conf.d/codekvast.d/conf.yaml
  notify: restart datadog-agent
  tags: datadog

- name: Create directories
  file: path={{ item }} state=directory owner=codekvast group=codekvast
  with_items:
  - "/opt/codekvast/bin"
  - "/opt/codekvast/{{ service_name }}"
  - "/var/log/codekvast/{{ service_name }}"

- name: "Install codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar"
  copy:
    src: ../../product/server/{{ service_name }}/build/libs/codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar
    dest: "/opt/codekvast/{{ service_name }}/codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar"
    owner: codekvast
    group: codekvast
    mode: 0700
  notify:
   - "restart codekvast service"
   - "send codekvast service installed event"

- name: "Install /opt/codekvast/{{ service_name }}/application.yml"
  template:
    src: "codekvast/{{ service_name }}/application.yml"
    dest: "/opt/codekvast/{{ service_name }}/application.yml"
    owner: codekvast
    group: codekvast
  notify:
  - "restart codekvast service"
  - "send codekvast service configured event"

- name: "Install /opt/codekvast/bin/jvm-crash-notifier.sh"
  template:
    src: "jvm-crash-notifier.sh"
    dest: "/opt/codekvast/bin/jvm-crash-notifier.sh"
    owner: codekvast
    group: codekvast
    mode: 0755

- name: "Install /etc/systemd/system/codekvast-{{ service_name }}.service"
  template:
    src: "systemd.service"
    dest: "/etc/systemd/system/codekvast-{{ service_name }}.service"
    owner: root
    group: root
  notify:
  - "systemctl daemon-reload"
  - "send codekvast service configured event"

- name: "Install /opt/codekvast/codekvast-javaagent-{{ codekvastVersion }}.jar"
  copy:
    src: ../../product/agent/java-agent/build/libs/codekvast-javaagent-{{ codekvastVersion }}.jar
    dest: "/opt/codekvast/codekvast-javaagent-{{ codekvastVersion }}.jar"
    owner: codekvast
    group: codekvast
    mode: 0700
  notify:
  - "restart codekvast service"
  - "send codekvast service configured event"

- name: "Install /opt/codekvast/{{ service_name }}/codekvast-agent.properties"
  template:
    src: codekvast-agent.properties
    dest: /opt/codekvast/{{ service_name }}/codekvast-agent.properties
    owner: codekvast
    group: codekvast
  notify:
  - "restart codekvast service"
  - "send codekvast service configured event"

- name: "Enable codekvast-{{ service_name }}"
  service:
    name: "codekvast-{{ service_name }}"
    enabled: yes

- name: "Start codekvast-{{ service_name }}"
  service:
    name: "codekvast-{{ service_name }}"
    state: started

- meta: flush_handlers

- name: "Wait until codekvast-{{ service_name }} has started"
  wait_for:
    port: "{{ service_port }}"
    state: started
    timeout: 60

- name: "Install /opt/codekvast/remove-old-versions.sh"
  copy:
    src: remove-old-versions.sh
    dest: /opt/codekvast/remove-old-versions.sh
    owner: codekvast
    group: codekvast
    mode: 0700

- name: "Execute /opt/codekvast/remove-old-versions.sh"
  command: /opt/codekvast/remove-old-versions.sh
  register: removed_versions
  changed_when: removed_versions.stdout != ""

- debug: var=removed_versions.stdout_lines
  when: removed_versions.stdout != ""

- name: "Install /etc/cron.daily/codekvast"
  copy:
    src: cron.daily/codekvast.sh
    dest: /etc/cron.daily/codekvast
    mode: 0755
  tags: cron
  register: cronscript

- name: "Execute /etc/cron.daily/codekvast"
  command: /etc/cron.daily/codekvast
  when: cronscript.changed
  tags: cron
