aws_region: eu-central-1
aws_stack_name: "Codekvast-{{ stack.customer }}-{{ stack.env }}"

# Max 32 characters in a target group name
aws_target_group_dashboard: "{{ aws_stack_name }}-d"
aws_target_group_login: "{{ aws_stack_name }}-l"
aws_target_group_backoffice: "{{ aws_stack_name }}-bo"

aws_ami_id: ami-060cde69 # Stock Ubuntu Server Xenial 16.04 LTS, 64-bit, SSD EBS

aws_common_tags:
  Name: "{{ aws_stack_name }}"
  Customer: "{{ stack.customer }}"
  Env: "{{ stack.env }}"
  Owner: Codekvast

aws_rds_tags:
  RDS: "true"

ec2_instance_profile_name: "Codekvast-CloudWatch"

s3_downloads_bucket: "io.codekvast.downloads"
