---
#--------------------------------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Admin application, which is an executable Spring Boot jar running as a systemd service
#--------------------------------------------------------------------------------------------------------------------------------
- name: Codekvast Admin Application
  hosts: tag_role_database
  user: ubuntu
  become: yes
  serial: 1

  vars_files:
  - vars/secrets.yml
  - vars/common.yml

  vars:
    server_type: database
    service_name: admin
    service_port: "{{ ports.admin.service }}"
    management_port: "{{ ports.admin.management }}"

  roles:
  - {role: Datadog.datadog, tags: [metrics, datadog, admin] }
  - {role: codekvast.spring-boot-service, tags: [service, admin], service_state: absent}
