---
#-----------------------------------------------------------------------------------------------------------
# Playbook that makes a backup of the production database to S3 and then restores it to the staging database
#-----------------------------------------------------------------------------------------------------------
- name:   "Make extra production database backup by means of mysqldump"
  hosts:  tag_Name_Codekvast_default_prod_database
  user:   ubuntu
  become: yes

  tasks:
  - name:  "Executing /root/mysqldump-backup extra in {{ tags.CNAME }}"
    shell: /root/mysqldump-backup extra

- name:   "Restore extra production database produced by mysqldump"
  hosts:  tag_Name_Codekvast_default_staging_database
  user:   ubuntu
  become: yes

  vars:
      mysql_backup_dir: '/backups/mariadb'
      s3_bucket:        "s3://io.codekvast.default.prod.backup"
      backup_file:      "mysqldump-extra.sql.gz"

  tasks:
  - name:  "Fetching {{ s3_bucket }}/{{ backup_file }} to {{ tags.CNAME }}:{{ mysql_backup_dir }}"
    shell: "s3cmd --config=/root/s3cfg --force get {{ s3_bucket }}/{{ backup_file }} {{ mysql_backup_dir }}"
  - name:  "Executing /root/mysqldump-restore {{ mysql_backup_dir }}/{{ backup_file }} --yes in {{ tags.CNAME }}"
    shell: "/root/mysqldump-restore {{ mysql_backup_dir }}/{{ backup_file }} --yes"
