---
#-----------------------------------------------------------------------------------------------------------
# Playbook that makes a extra backup of the production database to S3
#-----------------------------------------------------------------------------------------------------------
- name: Make production database backup
  hosts: tag_Name_Codekvast_default_prod_database

  become: yes

  tasks:
  - name: "Making {{ weekday }} database backup of {{ ec2_tag_CNAME }}"
    shell: /root/mariadb-backup {{ weekday }}
