---
#-----------------------------------------------------------------------------------------------------------
# Playbook that makes an extra backup of the database to S3
# It expects to be invoked with the ansible-playbook command line variables
#   -e srcEnv=eee where eee is either prod or staging
#   -e weekday=www where www is one of monday, tuesday, wednesday, thursday, friday, saturday, sunday or extra
#-----------------------------------------------------------------------------------------------------------
- name: "Make {{ srcEnv }} database backup"
  hosts: "tag_Name_Codekvast_default_{{ srcEnv }}_database"

  become: yes

  tasks:
  - name: "Making {{ weekday }} database backup of {{ tags.CNAME }} using mysqldump"
    shell: /root/mysqldump-backup {{ weekday }}
