---
#-----------------------------------------------------------------------------------------------------------
# Playbook for doing operating system maintenance
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Server
  hosts: all
  become: yes

  vars_files:
  - vars/common.yml

  roles:
  - {role: oefenweb.swapfile, tags: [os]}

  post_tasks:
  - name: Install swedish language pack
    package: name=language-pack-sv state=present

  - name: Cleanup APT cache to make room for upgrade
    apt: autoremove=yes autoclean=yes

  - name: Upgrade installed packages
    apt: purge=yes upgrade=safe
