---
#---------------------------------------------------------------
# Playbook that provisions the AWS RDS clusters
#---------------------------------------------------------------
- name:         AWS RDS clusters
  hosts:        all[0]
  connection:   local
  gather_facts: no

  vars_files:
    - vars/common.yml
    - vars/secrets.yml

  vars:
    env: staging

  tasks:
    - name:     "Find EC2 {{ env }} subnets owned by Codekvast"
      ec2_vpc_subnet_info:
        profile:     codekvast
        region:      "{{ aws_region }}"
        filters:
          "tag:Owner": "Codekvast"
          "tag:Env":   "{{ env }}"
      register: subnet_info

    - debug: var=subnet_info
      when:  _debug is defined and _debug

    - name:       "Create {{ env }} RDS subnet groups"
      rds_subnet_group:
        profile:             codekvast
        region:              "{{ aws_region }}"
        name:                "codekvast-{{ env }}"
        description:         "All Codekvast {{ env }} subnets"
        subnets:             "{{ subnet_info.subnets|map(attribute='id')|list }}"
        state:               present
      register:   subnet_group

    - debug: var=subnet_group
      when:  _debug is defined and _debug

    - name:     Find EC2 security groups
      ec2_group_info:
        profile:             codekvast
        region:              "{{ aws_region }}"
        filters:
          "tag:Owner": "Codekvast"
          "tag:Env":   "{{ env }}"
          "tag:RDS":   "true"
      register: security_group

    - debug: var=security_group
      when:  _debug is defined and _debug

    - name:       Create MariaDB RDS instances
      rds_instance:
        profile:                                         codekvast
        region:                                          "{{ aws_region }}"
        allocated_storage:                               20
        allow_major_version_upgrade:                     no
        auto_minor_version_upgrade:                      no
        availability_zone:                               "{{ aws_region }}a"
        backup_retention_period:                         7
        copy_tags_to_snapshot:                           yes
        db_instance_class:                               db.t3.micro
        db_instance_identifier:                          "codekvast-{{ env }}"
        db_subnet_group_name:                            "codekvast-{{ env }}"
        db_name:                                         codekvast
        engine:                                          mariadb
        engine_version:                                  "10.4"
        master_user_password:                            "{{ mariadb_root_password }}"
        master_username:                                 root
        port:                                            3306
        preferred_backup_window:                         "02:00-03:00"
        preferred_maintenance_window:                    "sun:04:00-sun:05:00"
        publicly_accessible:                             yes
        state:                                           present
        tags:
          Env:      "{{ env }}"
          Name:     Codekvast
          Owner:    Codekvast
        vpc_security_group_ids:                          "{{ security_group.security_groups|map(attribute='group_id') | list }}"
        wait:                                            yes
      register:   rds

    - debug: var=rds.endpoint
      when:  _debug is defined and _debug

    - name: "Create Codekvast database in MariaDB server at {{ rds.endpoint.address }}"
      mysql_db:
        login_host:     "{{ rds.endpoint.address }}"
        login_user:     root
        login_password: "{{ mariadb_root_password }}"
        name:           codekvast
        encoding:       utf8

    - name: "Create Codekvast application user in MariaDB server at {{ rds.endpoint.address }}"
      mysql_user:
        login_host:          "{{ rds.endpoint.address }}"
        login_user:          root
        login_password:      "{{ mariadb_root_password }}"
        name:                codekvast
        host:                "%"
        password:            "{{ mariadb_application_password }}"
        priv:                "codekvast.*:CREATE,ALTER,DROP,SELECT,INSERT,UPDATE,DELETE"

    - name: "Store MariaDB application password as a secret"
      aws_ssm_parameter_store:
        profile: codekvast
        region: "{{ aws_region }}"
        description: "Codekvast database application password"
        name: "mariadb_application_password"
        value: "{{ mariadb_application_password }}"
        string_type: "SecureString"
        overwrite_value: "always"

    - name: "Create CNAME db-{{ env}}.codekvast.io -> {{ rds.endpoint.address }}"
      route53:
        profile: codekvast # in ~/.boto
        zone: codekvast.io
        command: create
        overwrite: yes
        record: "db-{{ env }}.codekvast.io"
        ttl: 86400
        type: CNAME
        value: "{{ rds.endpoint.address }}"
      register: dns

    - debug: var=dns
      when:  _debug is defined and _debug
