---
#---------------------------------------------------------------
# Playbook which provisions the AWS infrastructure
#---------------------------------------------------------------
- name: AWS infrastructure stack
  hosts: all[0]
  connection: local
  gather_facts: no

  vars_files:
    - vars/common.yml
    - vars/secrets.yml

  tasks:
  - name: Create AWS stacks
    include_role: name=codekvast.aws-stack
    with_items: "{{ aws_stacks }}"
    loop_control:
      loop_var: stack
    tags: infra
