---
#---------------------------------------------------------------
# Playbook which uploads secrets to AWS SSM Parameter Store
#---------------------------------------------------------------
- name:         "Provision AWS secrets in {{ env }}"
  hosts:        localhost
  connection:   local
  gather_facts: no

  vars_files:
    - vars/common.yml
    - vars/secrets.yml

  vars:
    env: staging
    aws_common_tags:
      Owner: Codekvast
      Env:   "{{ env }}"
      LaunchType: Fargate

  tasks:
    - name: "Upload secrets to AWS SSM"
      aws_ssm_parameter_store:
        profile:         codekvast
        region:          "{{ aws_region }}"
        name:            "{{ item.name }}"
        description:     "{{ item.description }}"
        value:           "{{ item.value }}"
        string_type:     "SecureString"
        overwrite_value: "changed"
      with_items:
        - name:        "/codekvast/{{ env }}/mariadb/application_password"
          description: "Codekvast database application password"
          value:       "{{ secrets.mariadb[env].application_password }}"
        - name:        "/codekvast/{{ env }}/rabbitmq/url"
          description: "Codekvast RabbitMQ URL"
          value:       "{{ secrets.rabbitmq[env].url }}"
        - name:        "/codekvast/{{ env }}/jwt_secret"
          description: "The JWT secret"
          value:       "{{ secrets.codekvast.common.jwtSecret }}"
        - name:        "/codekvast/slackWebhookToken"
          description: "The Slack webhook token"
          value:       "{{ secrets.codekvast.common.slackWebhookToken }}"
        - name:        "/codekvast/datadog/apiKey"
          description: "The Datadog API key"
          value:       "{{ secrets.datadog.api_key }}"
        - name:        "/codekvast/datadog/applicationKey"
          description: "The Datadog application key"
          value:       "{{ secrets.datadog.app_key }}"
        - name:        "/codekvast/oauth2/{{ env }}/facebook/client-id"
          description: "The Facebook OAuth2 client id"
          value:       "{{ secrets.facebook.oauth[env].clientId }}"
        - name:        "/codekvast/oauth2/{{ env }}/facebook/client-secret"
          description: "The Facebook OAuth2 client secret"
          value:       "{{ secrets.facebook.oauth[env].clientSecret }}"
        - name:        "/codekvast/oauth2/{{ env }}/github/client-id"
          description: "The GitHub OAuth2 client id"
          value:       "{{ secrets.github.oauth[env].clientId }}"
        - name:        "/codekvast/oauth2/{{ env }}/github/client-secret"
          description: "The GitHub OAuth2 client secret"
          value:       "{{ secrets.github.oauth[env].clientSecret }}"
        - name:        "/codekvast/oauth2/{{ env }}/google/client-id"
          description: "The Google OAuth2 client id"
          value:       "{{ secrets.google.oauth[env].clientId }}"
        - name:        "/codekvast/oauth2/{{ env }}/google/client-secret"
          description: "The Google OAuth2 client secret"
          value:       "{{ secrets.google.oauth[env].clientSecret }}"
        - name:        "/codekvast/mail/username"
          description: "The AWS SES username"
          value:       "{{ secrets.aws.ses.username }}"
        - name:        "/codekvast/mail/password"
          description: "The AWS SES password"
          value:       "{{ secrets.aws.ses.password }}"
        - name:        "/codekvast/{{ env }}/login/cipherSecret"
          description: "The symmetric key used for encrypting database values"
          value:       "{{ secrets.codekvast.login.cipherSecret }}"
        - name:        "/codekvast/heroku/api/password"
          description: "The Heroku API password"
          value:       "{{ secrets.codekvast.heroku.provision.api.password }}"
        - name:        "/codekvast/heroku/api/ssoSalt"
          description: "The Heroku SSO salt"
          value:       "{{ secrets.codekvast.heroku.provision.api.ssoSalt }}"
        - name:        "/codekvast/heroku/oauth/clientId"
          description: "The Heroku OAuth client ID"
          value:       "{{ secrets.codekvast.heroku.oauth.clientId }}"
        - name:        "/codekvast/heroku/oauth/clientSecret"
          description: "The Heroku OAuth client secret"
          value:       "{{ secrets.codekvast.heroku.oauth.clientSecret }}"
        - name:        "/codekvast/s3/api_key"
          description: "The AWS access key id for S3 uploads"
          value:       "{{ secrets.aws.s3.api_key }}"
        - name:        "/codekvast/s3/secret_key"
          description: "The AWS secret key id for S3 uploads"
          value:       "{{ secrets.aws.s3.secret_key }}"

      loop_control:
        label: "{{ item.name }}"
      tags: [once, secrets]
