---
#-----------------------------------------------------------------------------------------------------------
# Playbook that restores a backup of the database
# It expects to be invoked with the ansible-playbook command line variables
#
#   -e srcEnv=eee where eee is either prod or staging
#   -e targetEnv=eee where eee is either prod or staging
#   -e weekday=www where www is one of monday, tuesday, wednesday, thursday, friday, saturday, sunday or extra
#-----------------------------------------------------------------------------------------------------------
- name: "Restore {{ srcEnv }} database backup from last {{ weekday }} to {{ targetEnv }}"
  hosts: "tag_Name_Codekvast_default_{{ targetEnv }}_database"

  become: yes

  vars:
    mysql_backup_dir: '/backups/mariadb'
    s3_bucket: "s3://io.codekvast.default.{{ srcEnv }}.backup"
    tarball: "mysqldump-{{ weekday }}.tar.gz"

  tasks:

  - name: "Fetching {{ s3_bucket }}/{{ tarball }} to {{ tags.CNAME }}:{{ mysql_backup_dir }}/{{ tarball }}"
    shell: "s3cmd --config=/root/s3cfg --force get {{ s3_bucket }}/{{ tarball }} {{ mysql_backup_dir }}"

  - name: "Restoring {{ mysql_backup_dir }}/{{ tarball }} in {{ tags.CNAME }}"
    shell: "/root/mysqldump-restore {{ mysql_backup_dir }}/{{ tarball }} --yes"
