---
#-----------------------------------------------------------------------------------------------------------
# Playbook that restores a backup of the database
# It expects to be invoked with the ansible-playbook command line variables
#
#   -e srcEnv=eee where eee is either prod or staging
#   -e targetEnv=eee where eee is either prod or staging
#   -e weekday=www where www is one of monday, tuesday, wednesday, thursday, friday, saturday, sunday or extra
#-----------------------------------------------------------------------------------------------------------
- name: "Restore {{ srcEnv }} database backup from last {{ weekday }} to {{ targetEnv }}"
  hosts: "tag_Name_Codekvast_default_{{ targetEnv }}_database"

  become: yes

  vars:
    mysql_backup_dir: '/backups/mariadb'
    s3_bucket: "s3://io.codekvast.default.{{ srcEnv }}.backup"
    sqldump: "mysqldump-{{ weekday }}.sql.gz"

  tasks:

  - name: Create backup directory
    file: path="{{ mysql_backup_dir }}" state=directory

  - name: "Fetching {{ s3_bucket }}/{{ sqldump }} to {{ tags.CNAME }}:{{ mysql_backup_dir }}/{{ sqldump }}"
    shell: "s3cmd --config=/root/s3cfg --force get {{ s3_bucket }}/{{ sqldump }} {{ mysql_backup_dir }}/{{ sqldump }}"

  - name: "Restoring {{ mysql_backup_dir }}/{{ sqldump }} in {{ tags.CNAME }}"
    shell: "/root/mysqldump-restore {{ mysql_backup_dir }}/{{ sqldump }} --yes"
