---
#-----------------------------------------------------------------------------------------------------------
# Playbook that restores a backup of the database
# It expects to be invoked with the ansible-playbook command line variables
#
#   -e env=eee where eee is either prod or staging
#   -e weekday=www where www is one of monday, tuesday, wednesday, thursday, friday, saturday, sunday or extra
#-----------------------------------------------------------------------------------------------------------
- name: "Restore production database backup from last {{ weekday }}"
  hosts: "tag_Name_Codekvast_default_{{ env }}_database"

  become: yes

  vars:
    mysql_backup_dir: '/backups/mariadb'
    s3_bucket: "s3://io.codekvast.default.prod.backup"
    tarball: "mariadb-backup-{{ weekday }}.tar.gz"

  tasks:

  - name: "Fetching {{ s3_bucket }}/{{ tarball }} to {{ ec2_tag_CNAME }}:{{ mysql_backup_dir }}"
    shell: "s3cmd --config=/root/s3cfg --force get {{ s3_bucket }}/{{ tarball }} {{ mysql_backup_dir }}"

  - name: "Restoring {{ mysql_backup_dir }}/{{ tarball }} in {{ ec2_tag_CNAME }}"
    shell: "/root/mariadb-restore {{ mysql_backup_dir }}/{{ tarball }} --yes"
