---
#---------------------------------------------------------------
# Playbook which updates the CNAMEs for all running instances
#---------------------------------------------------------------
- name: AWS infrastructure stack
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/common.yml

  tasks:
  - name: "Find running backend instances owned by Codekvast"
    local_action:
      module: ec2_instance_info
      profile: codekvast
      region: "{{ aws_region }}"
      filters:
        "tag:Owner": Codekvast
        "tag:role": backend
        "instance-state-name": running
    register: backend

  - debug: var=backend
    when: _debug is defined and _debug

  - name: "Find running database instances owned by Codekvast"
    local_action:
      module: ec2_instance_info
      profile: codekvast
      region: "{{ aws_region }}"
      filters:
        "tag:Owner": Codekvast
        "tag:role": database
        "instance-state-name": running
    register: database

  - debug: var=database
    when: _debug is defined and _debug

  - name: "Define the database instances' CNAMEs"
    local_action:
      module: route53
      profile: codekvast # in ~/.boto
      command: create
      overwrite: yes
      record: "{{ item.0.tags[item.1] }}"
      value: "{{ item.0.public_dns_name }}"
      ttl: 600
      type: CNAME
      zone: codekvast.io
    loop: "{{ database.instances|product(['CNAME'])|list }}"
    loop_control:
      label: "{{item.0.tags[item.1] + ' => ' + item.0.public_dns_name }}"

  - name: "Define the backend instances' CNAMEs"
    local_action:
      module: route53
      profile: codekvast # in ~/.boto
      command: create
      overwrite: yes
      record: "{{ item.0.tags[item.1] }}"
      value: "{{ item.0.public_dns_name }}"
      ttl: 600
      type: CNAME
      zone: codekvast.io
    loop: "{{ backend.instances|product(['CNAME0', 'CNAME1', 'CNAME2', 'CNAME3'])|list }}"
    loop_control:
      label: "{{item.0.tags[item.1] + ' => ' + item.0.public_dns_name }}"
