---
#-----------------------------------------------------------------------------------------------------------
# Playbook that upgrades MariaDB
#-----------------------------------------------------------------------------------------------------------
-   name:   Upgrade MariaDB
    hosts:  tag_role_database

    become: yes

    vars_files:
    - vars/secrets.yml
    - vars/common.yml

    vars:
        old_mariadb_version: '10.1'
        new_mariadb_version: '10.4'

    tasks:
    -   name:    "Install new MariaDB APT key"
        apt_key:
            id:        '0xF1656F24C74CD1D8'
            keyserver: hkp://keyserver.ubuntu.com:80
            state:     present

    -   name: "Define MariaDB {{ new_mariadb_version }} APT repository"
        apt_repository:
            filename:     mariadb
            repo:         "deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/{{ new_mariadb_version }}/ubuntu bionic main"
            state:        present

    -   name:    "Stop MariaDB"
        service: name=mariadb state=stopped
        ignore_errors: yes

    -   name:    "Uninstall MariaDB {{ old_mariadb_version }}"
        package: name={{ item }} state=absent
        with_items:
        - "mariadb-server-{{ old_mariadb_version }}"
        - "mariadb-client-{{ old_mariadb_version }}"

    -   name:    "Install MariaDB {{ new_mariadb_version }}"
        package: name={{ item }} state=present update_cache=yes
        with_items:
        - "mariadb-server-{{ new_mariadb_version }}"
        - "mariadb-client-{{ new_mariadb_version }}"

    -   name:    "Start MariaDB"
        service: name=mariadb state=started

    -   name:  "Execute mysql_upgrade"
        shell: mysql_upgrade
